-- =============================================================================
-- 19-more-tools.sql
-- 50 NEW tools across 6 categories
-- Distribution: hosting +9, ecommerce +8, business +6, ai-tools +9, marketing +9, saas +9
-- Generated: 2026-03-05
-- =============================================================================

-- ---------------------------------------------------------------------------
-- HOSTING (+9 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('pantheon', 'Pantheon', 'hosting', 'Managed WordPress & Drupal Hosting', 'WebOps platform for high-performance WordPress and Drupal sites', 'Pantheon provides a managed hosting platform specifically optimized for WordPress and Drupal websites. It offers integrated Dev, Test, and Live environments, automated HTTPS, global CDN, and powerful workflow tools for agencies and marketing teams managing multiple sites.', NULL, 'https://pantheon.io', 8.4, true, 41, 'USD', '{"multidev_environments": true, "global_cdn": true, "automated_https": true, "dev_test_live_workflow": true, "one_click_updates": true}', '["Excellent dev-test-live workflow for teams","Built-in CDN with edge caching","Strong uptime and performance guarantees","Great for agencies managing multiple sites"]', '["Pricing can be steep for small projects","Limited to WordPress and Drupal only","No email hosting included"]', '["Agencies managing multiple WordPress or Drupal sites","Enterprise marketing teams needing reliable WebOps","Developers who want Git-based deployment workflows"]', 'Pantheon is an excellent managed hosting choice for agencies and enterprises running WordPress or Drupal at scale, with a developer-friendly workflow that justifies the premium pricing.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('runcloud', 'RunCloud', 'hosting', 'Cloud Server Management Panel', 'Modern cloud server management panel for PHP applications', 'RunCloud is a cloud server management panel that simplifies deploying and managing PHP-based web applications on any cloud provider. It supports multiple PHP versions, automatic SSL via Let''s Encrypt, Git deployment, and server-level firewall management without requiring deep sysadmin knowledge.', NULL, 'https://runcloud.io', 8.0, false, 8, 'USD', '{"multi_php_versions": true, "git_deployment": true, "automatic_ssl": true, "server_firewall": true, "one_click_wordpress": true}', '["Works with any cloud provider (AWS, DO, Vultr, etc.)","Easy PHP version switching per application","Affordable pricing for multiple servers","Clean and intuitive dashboard"]', '["No free tier available","Limited to PHP-based applications","Backup features require higher plans"]', '["Developers managing multiple PHP sites across cloud providers","Small agencies needing affordable server management","WordPress developers who want more control than shared hosting"]', 'RunCloud is a cost-effective server management panel that bridges the gap between shared hosting simplicity and bare-metal server control for PHP developers.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('gridpane', 'GridPane', 'hosting', 'WordPress Server Management', 'Performance-focused WordPress server control panel', 'GridPane is a WordPress-specific server management platform that lets you deploy and manage optimized WordPress sites on cloud infrastructure from providers like Vultr, DigitalOcean, AWS, and Google Cloud. It features advanced caching stacks including Nginx, Redis, and OpenLiteSpeed.', NULL, 'https://gridpane.com', 8.2, false, 50, 'USD', '{"nginx_and_ols_stacks": true, "redis_object_cache": true, "automatic_backups": true, "staging_environments": true, "multisite_support": true}', '["Highly optimized WordPress performance stacks","Choice of Nginx or OpenLiteSpeed","Excellent security hardening features","Works with multiple cloud providers"]', '["Steeper learning curve than managed hosts","Minimum $50/month pricing","Requires choosing and paying for a separate cloud provider"]', '["WordPress developers who want maximum server performance","Agencies that need granular server control","High-traffic WordPress sites requiring optimized stacks"]', 'GridPane is ideal for WordPress professionals who want the performance of a finely tuned server stack without the complexity of manual server administration.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('spinupwp', 'SpinupWP', 'hosting', 'WordPress Server Management', 'Modern WordPress server control panel by Delicious Brains', 'SpinupWP is a modern cloud-based server control panel designed specifically for WordPress. Created by the team behind WP Migrate and Advanced Custom Fields, it provisions and manages WordPress servers on DigitalOcean, AWS, or any custom provider with optimized Nginx configurations.', NULL, 'https://spinupwp.com', 8.1, false, 12, 'USD', '{"optimized_nginx_config": true, "automatic_security_updates": true, "free_ssl_certificates": true, "one_click_staging": true, "server_monitoring": true}', '["Very clean and modern interface","Solid WordPress-specific optimizations","Created by trusted WordPress developers","Affordable per-server pricing"]', '["Limited to WordPress sites only","Fewer advanced features than GridPane","No built-in email server support"]', '["Solo WordPress developers wanting easy server management","Small teams deploying WordPress on cloud VPS","Developers who value simplicity over maximum configurability"]', 'SpinupWP offers a streamlined, developer-friendly approach to WordPress server management that prioritizes ease of use without sacrificing performance fundamentals.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('platform-sh', 'Platform.sh', 'hosting', 'Platform-as-a-Service', 'Unified PaaS for building, running, and scaling web applications', 'Platform.sh is a Platform-as-a-Service that provides a unified, secure, and scalable environment for running web applications. It supports PHP, Python, Node.js, Go, Java, and more, with infrastructure-as-code configuration, instant cloning of environments, and integrated CI/CD.', NULL, 'https://platform.sh', 8.3, true, 50, 'USD', '{"multi_language_support": true, "instant_environment_cloning": true, "infrastructure_as_code": true, "integrated_cicd": true, "automatic_tls": true}', '["True multi-language platform support","Instant cloning of full environments for testing","Strong enterprise security and compliance","Excellent for large development teams"]', '["Premium pricing compared to basic hosting","Can be complex for simple sites","Limited community compared to Heroku"]', '["Enterprise teams needing multi-language PaaS","Agencies managing complex multi-site environments","Organizations requiring SOC 2 compliant hosting"]', 'Platform.sh is a powerful PaaS for teams that need instant environment cloning, multi-language support, and enterprise-grade security in a single platform.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('hostiso', 'HostISO', 'hosting', 'Managed Cloud Hosting', 'Managed cloud hosting with dedicated resources and cPanel', 'HostISO provides managed cloud hosting with guaranteed dedicated resources, free cPanel, automated daily backups, and 24/7 support. They specialize in cloud VPS hosting with SSD storage across multiple data centers worldwide for WordPress, Magento, and custom applications.', NULL, 'https://hostiso.com', 7.6, false, 15, 'USD', '{"dedicated_resources": true, "free_cpanel": true, "automated_daily_backups": true, "ssd_storage": true, "multiple_data_centers": true}', '["Guaranteed dedicated CPU and RAM resources","Free cPanel license included","Good global data center coverage","Transparent and straightforward pricing"]', '["Smaller company with less brand recognition","Limited managed WordPress-specific features","Support response times can vary"]', '["Small businesses needing affordable dedicated cloud resources","Developers who prefer cPanel for server management","Sites requiring specific data center locations"]', 'HostISO offers solid managed cloud hosting with dedicated resources at competitive prices, making it a good choice for budget-conscious businesses that still need reliable performance.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('closte', 'Closte', 'hosting', 'Managed WordPress Hosting', 'Google Cloud-powered managed WordPress hosting', 'Closte is a managed WordPress hosting platform built on Google Cloud Platform infrastructure. It features a custom-built stack with Nginx, PHP-FPM, and Redis, automatic scaling, built-in CDN via Google Cloud CDN, and a pay-as-you-go pricing model that scales with traffic.', NULL, 'https://closte.com', 7.8, true, 10, 'USD', '{"google_cloud_infrastructure": true, "auto_scaling": true, "built_in_cdn": true, "redis_caching": true, "pay_as_you_go": true}', '["Google Cloud Platform infrastructure for reliability","True pay-as-you-go model with no fixed plans","Built-in CDN and edge caching","Automatic scaling handles traffic spikes"]', '["Costs can be unpredictable with traffic spikes","Smaller support team than major hosts","Limited migration assistance on lower tiers"]', '["WordPress sites with variable traffic patterns","Developers who want Google Cloud without managing infrastructure","Budget-conscious startups with growing sites"]', 'Closte provides an innovative pay-as-you-go WordPress hosting model on Google Cloud, ideal for sites with unpredictable traffic that want enterprise infrastructure without enterprise costs.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('devrims', 'Devrims', 'hosting', 'Managed Cloud Hosting', 'Managed cloud hosting across multiple cloud providers', 'Devrims is a managed cloud hosting platform that lets you deploy applications on AWS, Google Cloud, DigitalOcean, Vultr, and Linode from a single dashboard. It supports PHP, WordPress, Magento, Laravel, and other PHP frameworks with optimized server stacks and automated management.', NULL, 'https://devrims.com', 7.5, false, 22, 'USD', '{"multi_cloud_support": true, "optimized_php_stacks": true, "automated_backups": true, "staging_environments": true, "24_7_support": true}', '["Deploy on any major cloud provider from one panel","Good PHP framework support","Affordable managed hosting pricing","Helpful 24/7 support team"]', '["Less well-known in the market","Dashboard can feel dated","Limited non-PHP application support"]', '["PHP developers needing multi-cloud flexibility","Small businesses wanting managed cloud at lower cost","Laravel and Magento developers seeking optimized hosting"]', 'Devrims offers a practical multi-cloud managed hosting solution for PHP developers who want the flexibility to choose their cloud provider without managing the server themselves.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('10web', '10Web', 'hosting', 'AI-Powered WordPress Hosting', 'AI-powered WordPress hosting and website builder', '10Web combines managed WordPress hosting on Google Cloud with AI-powered website building tools. It offers automated PageSpeed optimization, real-time backups, built-in security, and an AI website builder that can recreate any website design as a WordPress site in minutes.', NULL, 'https://10web.io', 7.9, true, 10, 'USD', '{"ai_website_builder": true, "google_cloud_hosting": true, "automated_pagespeed_boost": true, "real_time_backups": true, "built_in_security": true}', '["AI builder can replicate existing site designs quickly","Automated PageSpeed optimization is genuinely useful","Google Cloud infrastructure for reliability","All-in-one hosting plus builder solution"]', '["AI-generated designs often need manual refinement","Higher plans needed for multiple sites","Builder limitations compared to dedicated page builders"]', '["Small businesses wanting quick WordPress site creation","Agencies needing fast prototyping from existing designs","WordPress users who want hosting and site building in one platform"]', '10Web is a compelling all-in-one platform that combines solid Google Cloud hosting with AI-powered site building, particularly useful for quickly launching WordPress sites.', 'published');

-- ---------------------------------------------------------------------------
-- ECOMMERCE (+8 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('snipcart', 'Snipcart', 'ecommerce', 'Shopping Cart Platform', 'Developer-friendly shopping cart you can add to any website', 'Snipcart is a developer-first shopping cart platform that can be added to any website or web application with a few lines of HTML and JavaScript. It supports custom product definitions, recurring subscriptions, digital goods, multi-currency, and integrates seamlessly with static sites and headless CMSes.', NULL, 'https://snipcart.com', 8.2, false, 0, 'USD', '{"html_based_integration": true, "subscription_support": true, "digital_goods": true, "multi_currency": true, "headless_cms_compatible": true}', '["Incredibly easy to add to any existing website","Works perfectly with static site generators","No monthly fee, just 2% transaction commission","Full customization via JavaScript and CSS"]', '["2% transaction fee adds up on high volume","Limited built-in marketing features","Smaller ecosystem than Shopify or WooCommerce"]', '["Developers adding ecommerce to static sites or blogs","JAMstack projects needing a lightweight cart","Small businesses wanting ecommerce without a full platform migration"]', 'Snipcart is the ideal shopping cart solution for developers who want to add ecommerce functionality to any website without being locked into a specific platform.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('medusa', 'Medusa', 'ecommerce', 'Open-Source Headless Commerce', 'Open-source headless commerce engine for developers', 'Medusa is an open-source headless commerce platform built with Node.js that gives developers the building blocks to create custom digital commerce experiences. It provides modules for orders, products, customers, payments, and fulfillment that can be composed and extended for any commerce use case.', NULL, 'https://medusajs.com', 8.5, true, 0, 'USD', '{"fully_open_source": true, "modular_architecture": true, "multi_region_support": true, "plugin_system": true, "rest_and_graphql_apis": true}', '["Completely open-source and self-hostable","Highly extensible modular architecture","Strong developer community and documentation","No vendor lock-in or transaction fees"]', '["Requires significant development effort to set up","No visual storefront builder included","Smaller plugin ecosystem than Shopify or WooCommerce"]', '["Developer teams building custom commerce experiences","Brands needing full control over their commerce stack","Companies migrating away from monolithic ecommerce platforms"]', 'Medusa is the leading open-source headless commerce engine, offering unmatched flexibility for developer teams that need to build custom ecommerce experiences without platform constraints.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('lemon-squeezy', 'Lemon Squeezy', 'ecommerce', 'Digital Commerce Platform', 'All-in-one platform for selling digital products and SaaS', 'Lemon Squeezy is a merchant of record platform designed for selling digital products, subscriptions, and SaaS. It handles global tax compliance, payment processing, fraud prevention, and customer management so creators and developers can focus on building products instead of financial infrastructure.', NULL, 'https://lemonsqueezy.com', 8.6, true, 0, 'USD', '{"merchant_of_record": true, "global_tax_compliance": true, "subscription_billing": true, "license_key_management": true, "affiliate_program": true}', '["Handles global sales tax and VAT automatically","No monthly fees, pay only per transaction","Built-in license key management for software","Clean checkout experience with high conversion rates"]', '["Higher per-transaction fees than Stripe alone","Limited storefront customization options","Fewer integrations than established platforms"]', '["Indie developers selling software or SaaS products","Digital creators selling courses, ebooks, or templates","SaaS companies needing simple subscription billing with tax compliance"]', 'Lemon Squeezy excels as a merchant of record for digital products and SaaS, removing the complexity of global tax compliance and payment processing for independent creators.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('paddle', 'Paddle', 'ecommerce', 'SaaS Billing & Payments', 'Complete payments infrastructure for SaaS companies', 'Paddle is a payment infrastructure platform that acts as a merchant of record for SaaS businesses. It handles subscriptions, invoicing, global tax compliance, payment methods, and revenue recovery, allowing SaaS companies to sell globally without setting up local entities or managing complex tax obligations.', NULL, 'https://paddle.com', 8.7, false, 0, 'USD', '{"merchant_of_record": true, "subscription_management": true, "global_tax_compliance": true, "revenue_recovery": true, "checkout_overlay": true}', '["Eliminates global sales tax and VAT complexity","Strong subscription dunning and revenue recovery","Supports 200+ countries with localized payments","Reduces SaaS churn with smart retry logic"]', '["Higher fees than direct Stripe integration","Payout schedules can be slower than Stripe","Less control over the payment flow"]', '["SaaS companies selling globally","Software businesses wanting to avoid tax compliance headaches","Subscription-based companies focused on reducing churn"]', 'Paddle is the go-to payment platform for SaaS companies that want to sell globally without building tax compliance, invoicing, and subscription infrastructure from scratch.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('commercetools', 'Commercetools', 'ecommerce', 'Enterprise Headless Commerce', 'API-first enterprise commerce platform built on MACH architecture', 'Commercetools is an enterprise-grade headless commerce platform built on MACH (Microservices, API-first, Cloud-native, Headless) architecture. It provides flexible APIs for product catalogs, shopping carts, orders, payments, and customer management, serving as the commerce engine for large-scale B2B and B2C operations.', NULL, 'https://commercetools.com', 8.8, false, 0, 'USD', '{"mach_architecture": true, "graphql_and_rest_apis": true, "multi_store_support": true, "b2b_and_b2c": true, "cloud_native_scaling": true}', '["Industry-leading MACH architecture for flexibility","Handles massive scale and complex catalogs","Strong B2B and B2C capabilities","Excellent API documentation and developer experience"]', '["Enterprise pricing not suitable for small businesses","Requires significant development investment","Long implementation timelines"]', '["Large enterprises needing flexible headless commerce","B2B companies with complex pricing and catalog needs","Organizations pursuing composable commerce architecture"]', 'Commercetools is the premier enterprise headless commerce platform, offering unmatched flexibility and scalability for large organizations ready to invest in composable commerce architecture.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('saleor', 'Saleor', 'ecommerce', 'Open-Source Headless Commerce', 'GraphQL-first open-source headless commerce platform', 'Saleor is an open-source, GraphQL-first headless commerce platform built with Python and Django. It provides a complete commerce backend with product management, orders, checkout, payments, and multi-channel support, along with a modern React-based dashboard for store management.', NULL, 'https://saleor.io', 8.1, true, 0, 'USD', '{"graphql_api": true, "open_source_core": true, "multi_channel": true, "react_dashboard": true, "plugin_architecture": true}', '["Modern GraphQL-first API design","Fully open-source with active community","Elegant React-based admin dashboard","Strong multi-channel commerce support"]', '["Smaller community than Magento or WooCommerce","Requires Python/Django expertise for customization","Cloud hosting version has enterprise pricing"]', '["Developer teams preferring GraphQL over REST","Python developers building custom storefronts","Mid-market businesses wanting open-source headless commerce"]', 'Saleor stands out with its modern GraphQL-first approach to headless commerce, making it an excellent open-source choice for developer teams that prefer Python and cutting-edge API design.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('printful', 'Printful', 'ecommerce', 'Print-on-Demand & Fulfillment', 'Print-on-demand dropshipping and fulfillment service', 'Printful is a print-on-demand dropshipping service that lets you sell custom-designed products without holding inventory. It integrates with major ecommerce platforms, handles printing, packaging, and shipping globally, and offers a product catalog including apparel, accessories, home decor, and more.', NULL, 'https://printful.com', 8.3, true, 0, 'USD', '{"print_on_demand": true, "global_fulfillment": true, "ecommerce_integrations": true, "mockup_generator": true, "warehousing_service": true}', '["No upfront inventory costs or minimum orders","Integrates with Shopify, Etsy, WooCommerce, and more","High-quality printing with consistent results","Built-in mockup generator for product images"]', '["Per-item costs are higher than bulk production","Shipping times can be long for international orders","Product catalog limited to printable items"]', '["Entrepreneurs starting custom merchandise businesses","Creators and artists selling branded products","Ecommerce stores wanting to add custom products without inventory risk"]', 'Printful is the leading print-on-demand platform for entrepreneurs and creators who want to sell custom products without the complexity and risk of managing inventory and fulfillment.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('bold-commerce', 'Bold Commerce', 'ecommerce', 'Ecommerce Customization Suite', 'Suite of ecommerce apps for subscriptions, pricing, and checkout', 'Bold Commerce provides a suite of ecommerce tools including subscription management, custom pricing rules, checkout customization, and upsell functionality. Their headless checkout and subscription APIs integrate with Shopify, BigCommerce, and custom storefronts to extend commerce capabilities beyond platform defaults.', NULL, 'https://boldcommerce.com', 7.9, true, 50, 'USD', '{"subscription_management": true, "custom_pricing_rules": true, "headless_checkout_api": true, "upsell_and_cross_sell": true, "multi_platform_support": true}', '["Powerful subscription management features","Headless checkout API enables custom experiences","Works across Shopify, BigCommerce, and custom builds","Strong upsell and cross-sell conversion tools"]', '["Pricing adds up when using multiple Bold apps","Can be complex to configure advanced features","Support quality varies by product"]', '["Shopify stores needing advanced subscription features","Ecommerce brands wanting custom checkout experiences","Businesses implementing complex pricing strategies"]', 'Bold Commerce offers powerful ecommerce extensions, particularly for subscriptions and custom checkout, that go well beyond what native ecommerce platforms provide out of the box.', 'published');

-- ---------------------------------------------------------------------------
-- BUSINESS (+6 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('scribe', 'Scribe', 'business', 'Process Documentation', 'Auto-generate step-by-step guides by recording your workflow', 'Scribe is a process documentation tool that automatically creates step-by-step guides by recording your screen as you perform a task. It captures screenshots, annotates each step, and produces shareable how-to documents that can be embedded in wikis, knowledge bases, or shared via link.', NULL, 'https://scribehow.com', 8.4, true, 23, 'USD', '{"auto_capture_steps": true, "screenshot_annotations": true, "shareable_guides": true, "team_workspace": true, "embed_anywhere": true}', '["Dramatically reduces time spent creating documentation","Auto-captured screenshots are accurate and well-annotated","Easy sharing and embedding in existing tools","Free tier is generous for individual use"]', '["Pro features require paid plan","Captured guides sometimes need manual editing","Desktop app required for non-browser workflows"]', '["Teams creating SOPs and training documentation","IT departments building knowledge bases","Managers documenting processes for new hires"]', 'Scribe eliminates the tedious work of creating step-by-step documentation, making it an essential tool for teams that rely on process documentation and training materials.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('tango', 'Tango', 'business', 'Workflow Documentation', 'Create how-to guides automatically as you work', 'Tango is a workflow documentation tool that captures your on-screen actions and automatically generates beautiful, step-by-step guides. It works as a browser extension, capturing clicks, typing, and navigation to produce editable guides with annotated screenshots that can be shared with teams.', NULL, 'https://tango.us', 8.1, true, 16, 'USD', '{"auto_workflow_capture": true, "annotated_screenshots": true, "team_sharing": true, "custom_branding": true, "integration_with_tools": true}', '["Effortless guide creation via browser extension","Clean and professional output format","Good free tier for individuals","Integrates with Notion, Confluence, and Slack"]', '["Browser extension only, no desktop app capture","Advanced features locked behind paid tiers","Guide editing can be limited"]', '["Customer success teams creating user guides","HR teams building onboarding documentation","Support teams documenting troubleshooting steps"]', 'Tango simplifies workflow documentation with its intuitive browser extension, producing professional guides that are easy to share and integrate into existing knowledge management systems.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('krisp', 'Krisp', 'business', 'AI Noise Cancellation', 'AI-powered noise cancellation and meeting assistant for calls', 'Krisp is an AI-powered noise cancellation and meeting assistant that removes background noise, echo, and other distractions from calls in real-time. It works with any communication app, transcribes meetings, generates summaries, and provides talk-time analytics to improve meeting effectiveness.', NULL, 'https://krisp.ai', 8.3, true, 8, 'USD', '{"ai_noise_cancellation": true, "echo_removal": true, "meeting_transcription": true, "meeting_summaries": true, "talk_time_analytics": true}', '["Best-in-class AI noise cancellation quality","Works with any conferencing app","Meeting transcription and summaries save time","Free tier includes daily usage minutes"]', '["Free tier has daily minute limits","Advanced meeting features require Pro plan","Requires desktop app installation"]', '["Remote workers in noisy environments","Sales teams needing clean call audio","Teams wanting automatic meeting notes and summaries"]', 'Krisp delivers exceptional AI noise cancellation alongside useful meeting intelligence features, making it essential for remote workers and teams who spend significant time on calls.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('claap', 'Claap', 'business', 'Video Collaboration', 'Async video collaboration and meeting recording for teams', 'Claap is a video collaboration platform that helps teams communicate asynchronously through screen recordings and meeting recordings. It automatically transcribes and summarizes meetings, creates searchable video libraries, and enables threaded video discussions, reducing the need for real-time meetings while keeping teams aligned.', NULL, 'https://claap.io', 8.0, true, 10, 'USD', '{"screen_recording": true, "meeting_recording": true, "auto_transcription": true, "ai_summaries": true, "threaded_video_comments": true}', '["AI-generated meeting summaries save review time","Threaded video discussions enable async collaboration","Searchable transcript library across all recordings","Integrates with Slack, Notion, and Linear"]', '["Smaller user base than Loom","Free tier has recording limits","Video editing features are basic"]', '["Remote teams wanting to reduce meeting load","Product teams sharing async updates and demos","Companies building searchable video knowledge bases"]', 'Claap is an excellent async video collaboration tool that goes beyond simple recording by adding AI summaries, threaded discussions, and searchable transcripts for team knowledge sharing.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('whimsical', 'Whimsical', 'business', 'Visual Collaboration', 'Visual workspace for flowcharts, wireframes, and mind maps', 'Whimsical is a visual collaboration tool that provides an integrated workspace for creating flowcharts, wireframes, mind maps, and sticky notes. It emphasizes speed and simplicity, with smart formatting that automatically aligns and styles elements as you create them.', NULL, 'https://whimsical.com', 8.3, true, 10, 'USD', '{"flowcharts": true, "wireframes": true, "mind_maps": true, "sticky_notes": true, "real_time_collaboration": true}', '["Exceptionally fast and intuitive to use","Auto-formatting produces clean, professional diagrams","All visual tools in one workspace","Good free tier for personal use"]', '["Less powerful than dedicated diagramming tools like Lucidchart","Limited export format options","No offline mode available"]', '["Product managers creating quick wireframes and flows","Teams brainstorming with mind maps and sticky notes","Designers who need fast, clean diagrams without fuss"]', 'Whimsical excels at making visual thinking fast and beautiful, offering the perfect balance of simplicity and capability for teams that value speed over exhaustive features.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('slite', 'Slite', 'business', 'Team Knowledge Base', 'AI-powered knowledge base for modern teams', 'Slite is a team knowledge base powered by AI that helps teams organize, find, and share internal knowledge. It features an AI assistant that can answer questions based on your team documentation, smart organization with automatic suggestions, and a clean writing experience for creating and maintaining docs.', NULL, 'https://slite.com', 7.9, true, 8, 'USD', '{"ai_powered_search": true, "knowledge_organization": true, "team_collaboration": true, "template_library": true, "integrations": true}', '["AI assistant answers questions from your docs","Clean and distraction-free writing experience","Automatic organization suggestions save time","Affordable pricing for small teams"]', '["Smaller feature set than Notion or Confluence","AI accuracy depends on documentation quality","Limited customization compared to competitors"]', '["Small teams building their first knowledge base","Remote teams needing quick access to internal docs","Startups that want AI-powered documentation without complexity"]', 'Slite is a focused knowledge base tool that uses AI to make finding and using internal documentation genuinely easy, ideal for small teams that want simplicity over power-user features.', 'published');

-- ---------------------------------------------------------------------------
-- AI-TOOLS (+9 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('v0', 'v0 by Vercel', 'ai-tools', 'AI Code Generation', 'AI-powered UI generation tool by Vercel', 'v0 is an AI-powered generative UI tool by Vercel that creates React components and full page layouts from text prompts and images. It generates production-ready code using shadcn/ui and Tailwind CSS, enabling rapid prototyping and frontend development without manual coding.', NULL, 'https://v0.dev', 8.8, true, 20, 'USD', '{"text_to_ui": true, "image_to_code": true, "shadcn_tailwind_output": true, "iterative_refinement": true, "one_click_deploy": true}', '["Generates production-quality React components","Output uses modern shadcn/ui and Tailwind CSS","Iterative refinement through conversation","Free tier allows meaningful experimentation"]', '["Limited to React and Next.js ecosystem","Generated code sometimes needs manual cleanup","Complex layouts may not match expectations"]', '["Frontend developers prototyping UI quickly","Designers who want to generate code from mockups","Next.js developers accelerating component development"]', 'v0 is a breakthrough tool for rapid UI prototyping, generating surprisingly high-quality React components that often need minimal adjustment for production use.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('bolt-new', 'Bolt.new', 'ai-tools', 'AI Full-Stack Development', 'AI-powered full-stack web development in the browser', 'Bolt.new by StackBlitz is an AI-powered development environment that generates, runs, and deploys full-stack web applications directly in the browser. It supports multiple frameworks including React, Vue, Svelte, and Node.js, creating complete applications with frontend, backend, and database from natural language descriptions.', NULL, 'https://bolt.new', 8.6, true, 20, 'USD', '{"full_stack_generation": true, "in_browser_development": true, "multi_framework_support": true, "instant_deployment": true, "ai_debugging": true}', '["Generates complete full-stack applications from prompts","Runs everything in the browser with no local setup","Supports multiple frameworks and languages","Quick deployment to production"]', '["Token usage can run out quickly on complex projects","Generated code quality varies with complexity","Less control than traditional development environments"]', '["Entrepreneurs prototyping web applications quickly","Developers exploring new frameworks","Non-technical founders building MVPs"]', 'Bolt.new democratizes full-stack development by letting anyone create and deploy web applications through conversation, making it an impressive rapid prototyping tool.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('lovable', 'Lovable', 'ai-tools', 'AI Application Builder', 'AI-powered application builder for non-technical creators', 'Lovable (formerly GPT Engineer) is an AI-powered application builder that creates full-stack web applications from natural language descriptions. It generates React frontends with Tailwind CSS, connects to Supabase backends, and handles authentication, database design, and API integration through conversational prompts.', NULL, 'https://lovable.dev', 8.3, true, 20, 'USD', '{"natural_language_to_app": true, "supabase_integration": true, "authentication_built_in": true, "github_sync": true, "responsive_design": true}', '["Creates functional full-stack apps from descriptions","Built-in Supabase backend integration","GitHub sync for version control","Responsive designs generated by default"]', '["Supabase-centric architecture limits backend choices","Complex business logic often needs manual coding","Can be expensive with heavy iteration"]', '["Non-technical founders building product MVPs","Designers who want to create functional prototypes","Small teams needing internal tools quickly"]', 'Lovable is a powerful AI application builder that makes full-stack development accessible to non-technical users, with particularly strong integration between frontend and Supabase backend.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('photoroom', 'PhotoRoom', 'ai-tools', 'AI Image Editing', 'AI-powered background removal and product photo editor', 'PhotoRoom is an AI-powered image editing tool specializing in background removal, product photography enhancement, and marketing visual creation. It instantly removes backgrounds, generates professional product photos with AI-created scenes, and provides batch processing for ecommerce catalogs.', NULL, 'https://photoroom.com', 8.5, true, 10, 'USD', '{"ai_background_removal": true, "ai_generated_backgrounds": true, "batch_processing": true, "brand_kit": true, "api_access": true}', '["Best-in-class AI background removal accuracy","AI-generated product photography saves studio costs","Batch processing handles large catalogs efficiently","Available as mobile app, web app, and API"]', '["Watermarks on free tier exports","Advanced features require Pro subscription","AI backgrounds can look generic without customization"]', '["Ecommerce sellers creating product listing images","Social media managers needing quick visual content","Marketplaces requiring consistent product photography"]', 'PhotoRoom is the leading AI tool for product photography, offering background removal and scene generation that dramatically reduces the cost and time of creating professional ecommerce imagery.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('krea-ai', 'Krea AI', 'ai-tools', 'AI Image Generation', 'Real-time AI image generation and enhancement platform', 'Krea AI is a creative AI platform offering real-time image generation, upscaling, and enhancement tools. Its standout feature is real-time generation that updates images as you draw or type, along with AI upscaling that enhances image resolution up to 4x while adding realistic detail.', NULL, 'https://krea.ai', 8.0, true, 24, 'USD', '{"real_time_generation": true, "ai_upscaling": true, "image_enhancement": true, "style_transfer": true, "video_generation": true}', '["Real-time generation provides instant visual feedback","Excellent AI upscaling quality","Intuitive canvas-based editing interface","Free tier for basic generation"]', '["Premium features require subscription","Generation quality varies by prompt","Less community and documentation than Midjourney"]', '["Designers exploring AI-assisted creative workflows","Content creators needing quick image generation","Photographers wanting AI-powered image enhancement"]', 'Krea AI stands out with its real-time generation capability that makes AI image creation feel interactive and responsive, alongside impressive upscaling features for enhancing existing images.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('napkin-ai', 'Napkin AI', 'ai-tools', 'AI Visual Content', 'Turn text into professional visuals and diagrams instantly', 'Napkin AI transforms text content into professional visuals, diagrams, infographics, and illustrations automatically. It analyzes written content and generates contextually relevant visuals that can be customized, exported, and used in presentations, blog posts, social media, and documentation.', NULL, 'https://napkin.ai', 7.8, true, 18, 'USD', '{"text_to_visuals": true, "auto_diagram_generation": true, "customizable_styles": true, "export_formats": true, "brand_colors": true}', '["Generates visuals from text content automatically","Multiple visual styles and templates available","Useful for presentations and blog post graphics","Free tier for basic usage"]', '["Visual quality varies depending on content complexity","Limited control over exact visual layout","Cannot replace professional graphic design for complex needs"]', '["Content marketers creating blog post visuals","Presenters needing quick diagram generation","Technical writers illustrating concepts"]', 'Napkin AI is a clever tool for automatically generating visuals from text content, saving significant time for content creators who regularly need diagrams and illustrations.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('codeium', 'Codeium', 'ai-tools', 'AI Code Assistant', 'Free AI-powered code completion and chat for developers', 'Codeium (now Windsurf, but Codeium still operates as the code completion engine) provides AI-powered code autocomplete, search, and chat across 70+ programming languages. It integrates with major IDEs including VS Code, JetBrains, Vim, and Emacs, offering fast and accurate code suggestions with a generous free tier.', NULL, 'https://codeium.com', 8.4, true, 12, 'USD', '{"code_autocomplete": true, "70_plus_languages": true, "multi_ide_support": true, "ai_chat": true, "code_search": true}', '["Generous free tier with unlimited completions","Supports 70+ programming languages","Fast completion speed with low latency","Works in all major IDEs and editors"]', '["Code suggestions sometimes less accurate than Copilot","Enterprise features require paid plan","Chat capabilities less advanced than Claude or ChatGPT"]', '["Individual developers wanting free AI code completion","Teams looking for a Copilot alternative","Developers using less common IDEs or editors"]', 'Codeium offers an impressive free AI code completion experience that rivals paid alternatives, making it an excellent choice for developers who want AI assistance without subscription costs.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('mem-ai', 'Mem', 'ai-tools', 'AI Note-Taking', 'AI-powered self-organizing workspace for notes and knowledge', 'Mem is an AI-powered note-taking and knowledge management tool that automatically organizes your notes, surfaces relevant information, and generates content based on your knowledge base. It uses AI to connect related notes, answer questions from your data, and draft content using your existing knowledge.', NULL, 'https://mem.ai', 7.7, true, 15, 'USD', '{"ai_organization": true, "smart_search": true, "knowledge_graph": true, "ai_writing_assistant": true, "meeting_notes": true}', '["AI automatically organizes and connects notes","Smart search finds relevant information quickly","AI can draft content from your knowledge base","Clean and fast writing interface"]', '["Limited formatting compared to Notion","Organization relies heavily on AI, less manual control","Smaller ecosystem and fewer integrations"]', '["Knowledge workers managing large volumes of notes","Professionals who want AI to organize their thinking","Writers who reference past notes and research frequently"]', 'Mem takes a unique AI-first approach to note-taking, automatically organizing and connecting information in ways that traditional tools require manual effort to achieve.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('perplexity-spaces', 'Perplexity Spaces', 'ai-tools', 'AI Research & Collaboration', 'Collaborative AI research spaces for team knowledge building', 'Perplexity Spaces is a collaborative research feature within Perplexity AI that lets teams create shared research environments. Team members can contribute AI-powered searches, organize findings, upload documents for AI analysis, and build collective knowledge bases with source-cited research.', NULL, 'https://perplexity.ai/spaces', 8.2, true, 20, 'USD', '{"collaborative_research": true, "source_citations": true, "document_upload": true, "shared_knowledge_base": true, "ai_powered_search": true}', '["AI research with reliable source citations","Collaborative spaces for team research","Upload documents for AI-powered analysis","Clean interface focused on research quality"]', '["Requires Perplexity Pro for full Spaces features","Limited compared to dedicated knowledge management tools","Cannot replace deep domain-specific research databases"]', '["Research teams conducting collaborative investigations","Analysts needing cited sources for reports","Teams building shared knowledge repositories"]', 'Perplexity Spaces extends AI-powered research into collaborative territory, making it valuable for teams that need to conduct, organize, and share well-sourced research.', 'published');

-- ---------------------------------------------------------------------------
-- MARKETING (+9 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('beehiiv', 'beehiiv', 'marketing', 'Newsletter Platform', 'Modern newsletter platform built for growth', 'beehiiv is a newsletter platform designed for creators and media companies who want to build, monetize, and grow their email audience. It offers a built-in referral program, ad network, premium subscriptions, advanced analytics, and website builder specifically optimized for newsletter businesses.', NULL, 'https://beehiiv.com', 8.7, true, 39, 'USD', '{"newsletter_editor": true, "referral_program": true, "ad_network": true, "premium_subscriptions": true, "advanced_analytics": true}', '["Built-in referral program drives organic growth","Ad network provides monetization from day one","Modern editor with great design flexibility","Free tier supports up to 2,500 subscribers"]', '["Advanced features require Scale plan","Less established than Mailchimp or ConvertKit","Limited automation compared to dedicated email marketing tools"]', '["Newsletter creators building a media business","Writers monetizing their audience","Content creators wanting built-in growth tools"]', 'beehiiv is the fastest-growing newsletter platform for good reason, offering growth and monetization tools that are purpose-built for the creator economy in ways traditional email platforms cannot match.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('customer-io', 'Customer.io', 'marketing', 'Marketing Automation', 'Automated messaging platform for data-driven marketers', 'Customer.io is a marketing automation platform that enables businesses to create sophisticated, data-driven messaging campaigns across email, push notifications, SMS, in-app messages, and webhooks. It uses real-time customer data and event-based triggers to deliver personalized communication at scale.', NULL, 'https://customer.io', 8.6, false, 100, 'USD', '{"multi_channel_messaging": true, "event_based_triggers": true, "visual_workflow_builder": true, "ab_testing": true, "real_time_data": true}', '["Powerful event-driven automation engine","Supports email, push, SMS, in-app, and webhooks","Visual workflow builder is intuitive and flexible","Excellent data handling and segmentation"]', '["Starting price of $100/month is steep for small teams","Learning curve for advanced segmentation","No free tier available"]', '["SaaS companies with complex user journeys","Product-led growth teams automating lifecycle messaging","Data-driven marketing teams needing multi-channel campaigns"]', 'Customer.io is the preferred automation platform for product-led companies that need event-driven, multi-channel messaging triggered by real-time user behavior.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('notion-sites', 'Notion Sites', 'marketing', 'Website Builder', 'Publish beautiful websites directly from Notion pages', 'Notion Sites lets you publish Notion pages as standalone websites with custom domains, SEO settings, and analytics. It transforms Notion documents into professional web pages with customizable themes, navigation, and branding, enabling teams to create marketing pages, documentation sites, and blogs without a traditional CMS.', NULL, 'https://notion.so/product/sites', 7.8, true, 10, 'USD', '{"notion_to_website": true, "custom_domains": true, "seo_settings": true, "custom_themes": true, "analytics": true}', '["Publish directly from existing Notion content","No coding required for professional websites","Maintains Notion collaborative editing workflow","Custom domains and basic SEO support"]', '["Limited design customization compared to dedicated builders","Performance can lag behind purpose-built platforms","Advanced features require Notion Plus or Business plans"]', '["Teams already using Notion for documentation","Startups needing a quick landing page","Internal teams publishing knowledge bases externally"]', 'Notion Sites is a natural extension for teams already using Notion, turning internal pages into public websites with minimal effort, though it cannot replace dedicated website builders for complex sites.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('instantly', 'Instantly', 'marketing', 'Cold Email Outreach', 'Cold email outreach platform with unlimited sending accounts', 'Instantly is a cold email outreach platform that allows connecting unlimited email accounts for scaled outbound campaigns. It features AI-powered email warmup, lead database, sequence automation, email validation, and deliverability tools designed to maximize inbox placement and response rates.', NULL, 'https://instantly.ai', 8.3, false, 30, 'USD', '{"unlimited_email_accounts": true, "ai_email_warmup": true, "lead_database": true, "sequence_automation": true, "email_validation": true}', '["Unlimited email accounts for scaled outreach","AI warmup improves deliverability significantly","Built-in lead database saves time on prospecting","Clean and intuitive campaign interface"]', '["Cold email reputation risks if misused","Lead database quality varies by industry","No free tier available"]', '["Sales teams running cold email campaigns at scale","B2B startups building outbound pipeline","Agencies managing outreach for multiple clients"]', 'Instantly is the leading cold email platform for teams that need to scale outbound outreach, with best-in-class warmup and deliverability features that maximize inbox placement.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('apollo-io', 'Apollo.io', 'marketing', 'Sales Intelligence & Outreach', 'All-in-one sales intelligence and engagement platform', 'Apollo.io combines a database of over 275 million contacts with sales engagement tools including email sequences, calling, LinkedIn automation, and deal management. It serves as a unified platform for prospecting, enrichment, outreach, and pipeline management for B2B sales teams.', NULL, 'https://apollo.io', 8.5, true, 49, 'USD', '{"contact_database": true, "email_sequences": true, "linkedin_integration": true, "data_enrichment": true, "deal_management": true}', '["Massive contact database with good data quality","All-in-one prospecting and outreach platform","Generous free tier with 10,000 credits","Strong email sequence and automation tools"]', '["Data accuracy varies by region and industry","Can feel overwhelming with so many features","Higher tiers needed for advanced filters and integrations"]', '["B2B sales teams building prospecting pipelines","SDRs and BDRs doing outbound outreach","Revenue teams wanting unified prospecting and engagement"]', 'Apollo.io is the most comprehensive all-in-one sales intelligence and engagement platform, combining a massive contact database with powerful outreach tools at competitive pricing.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('phantom-buster', 'PhantomBuster', 'marketing', 'Growth Automation', 'Cloud-based automation tool for lead generation and scraping', 'PhantomBuster is a cloud-based automation platform that provides pre-built workflows (Phantoms) for extracting data from social media, websites, and directories. It specializes in LinkedIn automation, lead generation, and data enrichment, running automations in the cloud without requiring local setup.', NULL, 'https://phantombuster.com', 7.8, true, 56, 'USD', '{"pre_built_automations": true, "linkedin_automation": true, "data_extraction": true, "cloud_execution": true, "crm_integration": true}', '["100+ pre-built automations ready to use","Powerful LinkedIn data extraction and outreach","Cloud-based execution requires no local resources","Integrates with CRMs for lead pipeline automation"]', '["Can violate LinkedIn Terms of Service if misused","Pricing is relatively high for individual users","Data extraction quality depends on source platform limits"]', '["Growth hackers automating lead generation","Sales teams extracting LinkedIn prospect data","Marketers building targeted lead lists from social data"]', 'PhantomBuster is a powerful growth automation tool that simplifies lead generation through pre-built social media and web scraping workflows, though users should be mindful of platform terms of service.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('webflow', 'Webflow', 'marketing', 'Visual Web Design & CMS', 'Professional visual web design platform with built-in CMS', 'Webflow is a visual web design and development platform that produces clean, production-ready code without manual coding. It combines a powerful visual builder with a flexible CMS, hosting, and ecommerce capabilities, enabling designers to create complex, responsive websites with professional-grade interactions and animations.', NULL, 'https://webflow.com', 9.0, true, 14, 'USD', '{"visual_web_builder": true, "built_in_cms": true, "interactions_and_animations": true, "responsive_design": true, "clean_code_output": true}', '["Professional-quality websites without writing code","Generates clean, semantic HTML and CSS","Powerful CMS for content-driven sites","Best-in-class interaction and animation tools"]', '["Steep learning curve for non-designers","CMS has limitations for very complex data models","Ecommerce features less mature than Shopify"]', '["Web designers building client sites without developers","Marketing teams managing content-driven websites","Agencies wanting to design and launch sites faster"]', 'Webflow is the industry-leading visual web design platform, producing professional-quality websites with clean code that bridges the gap between design tools and development.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('posthog', 'PostHog', 'marketing', 'Product Analytics', 'Open-source product analytics suite with session recording', 'PostHog is an open-source product analytics platform that combines event analytics, session recording, feature flags, A/B testing, and surveys in a single platform. It can be self-hosted or used as a cloud service, giving teams complete control over their analytics data while providing a comprehensive product analytics toolkit.', NULL, 'https://posthog.com', 8.8, true, 0, 'USD', '{"event_analytics": true, "session_recording": true, "feature_flags": true, "ab_testing": true, "surveys": true}', '["All-in-one product analytics suite","Generous free tier with 1M events/month","Self-hosting option for data control","Open-source with strong community"]', '["Can be complex to set up and configure","Self-hosting requires infrastructure management","UI less polished than Amplitude or Mixpanel"]', '["Product teams wanting unified analytics and experimentation","Privacy-conscious companies needing self-hosted analytics","Startups looking for free comprehensive product analytics"]', 'PostHog is the most comprehensive open-source product analytics platform, uniquely combining analytics, session recording, feature flags, and experimentation in one tool with a generous free tier.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('clearscope', 'Clearscope', 'marketing', 'Content Optimization', 'AI-powered content optimization for search performance', 'Clearscope is an AI-powered content optimization platform that analyzes top-ranking content for any keyword and provides actionable recommendations to improve search performance. It grades content in real-time, suggests relevant terms and topics, and integrates with Google Docs and WordPress for seamless optimization workflows.', NULL, 'https://clearscope.io', 8.4, false, 170, 'USD', '{"content_grading": true, "keyword_analysis": true, "competitor_content_analysis": true, "google_docs_integration": true, "wordpress_plugin": true}', '["Highly accurate content optimization recommendations","Real-time content grading as you write","Seamless Google Docs and WordPress integration","Competitive analysis reveals content gaps"]', '["Premium pricing starting at $170/month","Only focused on content optimization, not full SEO","No free tier or trial period"]', '["Content teams focused on organic search performance","SEO agencies optimizing client content at scale","Publishers wanting data-driven content improvement"]', 'Clearscope is the gold standard for content optimization, providing precise, data-driven recommendations that consistently improve search rankings for teams willing to invest in premium pricing.', 'published');

-- ---------------------------------------------------------------------------
-- SAAS (+9 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('height', 'Height', 'saas', 'Project Management', 'Autonomous project management tool with AI task management', 'Height is a project management tool that uses AI to automate routine project management tasks. It features autonomous task triage, status updates, duplicate detection, and smart backlogs that automatically organize and prioritize work, reducing the manual overhead of keeping projects organized.', NULL, 'https://height.app', 8.1, true, 7, 'USD', '{"ai_task_triage": true, "autonomous_status_updates": true, "smart_backlogs": true, "duplicate_detection": true, "cross_team_views": true}', '["AI automates tedious project management tasks","Clean and modern interface design","Affordable pricing per user","Cross-team visibility without complexity"]', '["Smaller ecosystem than Jira or Asana","AI features still maturing","Limited third-party integrations"]', '["Engineering teams wanting AI-assisted project management","Small teams tired of manual task triage","Product teams seeking simpler alternatives to Jira"]', 'Height brings a refreshing AI-first approach to project management, automating the busywork that makes traditional tools feel like a burden rather than a help.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('plane', 'Plane', 'saas', 'Project Management', 'Open-source project management for product teams', 'Plane is an open-source project management tool designed for product and engineering teams. It provides issue tracking, cycles (sprints), modules, custom views, and a product roadmap, offering a clean alternative to Jira and Linear that can be self-hosted for complete data control.', NULL, 'https://plane.so', 8.3, true, 7, 'USD', '{"issue_tracking": true, "cycles_and_sprints": true, "modules": true, "custom_views": true, "self_hosting": true}', '["Open-source with self-hosting option","Clean interface comparable to Linear","Generous free tier for small teams","Active development with frequent updates"]', '["Fewer integrations than established competitors","Some advanced features still in development","Self-hosting requires technical expertise"]', '["Product teams wanting an open-source Jira alternative","Startups preferring self-hosted project management","Engineering teams who value clean, focused project tools"]', 'Plane is a compelling open-source alternative to Linear and Jira, offering a clean project management experience with the added benefit of self-hosting for data-conscious teams.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('twenty-crm', 'Twenty CRM', 'saas', 'Open-Source CRM', 'Modern open-source CRM built for the next generation of sales teams', 'Twenty CRM is a modern, open-source customer relationship management platform that offers a clean interface, customizable data models, email sync, activity tracking, and a powerful GraphQL API. It aims to be the open-source alternative to Salesforce with a developer-friendly architecture and self-hosting capability.', NULL, 'https://twenty.com', 7.6, true, 9, 'USD', '{"custom_data_models": true, "email_sync": true, "graphql_api": true, "activity_tracking": true, "self_hosting": true}', '["Modern and clean UI unlike legacy CRMs","Fully customizable data model","Open-source with self-hosting option","Developer-friendly GraphQL API"]', '["Still early in development with some missing features","Smaller plugin ecosystem than established CRMs","Limited reporting and dashboards currently"]', '["Startups wanting a modern CRM without legacy complexity","Developer teams building custom CRM workflows","Small businesses seeking an open-source Salesforce alternative"]', 'Twenty CRM brings a refreshingly modern approach to open-source CRM, though it is still maturing and best suited for early adopters who value developer experience and customizability.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('chatwoot', 'Chatwoot', 'saas', 'Customer Support', 'Open-source customer engagement platform', 'Chatwoot is an open-source customer engagement platform that consolidates conversations from website live chat, email, social media, and messaging apps into a single dashboard. It offers real-time chat, chatbot automation, canned responses, team collaboration, and comprehensive reporting for support teams.', NULL, 'https://chatwoot.com', 8.0, true, 19, 'USD', '{"omnichannel_inbox": true, "live_chat_widget": true, "chatbot_automation": true, "team_collaboration": true, "self_hosting": true}', '["Open-source with self-hosting option","Unified inbox across all channels","Good automation and chatbot capabilities","Active community and regular updates"]', '["Less feature-rich than Intercom or Zendesk","Self-hosted version requires server management","Enterprise features still developing"]', '["Small businesses needing affordable omnichannel support","Teams wanting self-hosted customer support software","Startups looking for an Intercom alternative"]', 'Chatwoot is the strongest open-source alternative to Intercom and Zendesk, providing solid omnichannel customer support capabilities with the option to self-host for data sovereignty.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('pagerduty', 'PagerDuty', 'saas', 'Incident Management', 'Digital operations management platform for incident response', 'PagerDuty is a digital operations management platform that helps teams detect, triage, and resolve critical incidents in real-time. It aggregates alerts from monitoring tools, routes them to the right responders with intelligent escalation, and provides post-incident analytics to improve operational resilience.', NULL, 'https://pagerduty.com', 8.6, true, 21, 'USD', '{"alert_aggregation": true, "intelligent_routing": true, "on_call_scheduling": true, "incident_workflows": true, "postmortem_analytics": true}', '["Industry-standard incident management platform","Intelligent alert grouping reduces noise","Robust on-call scheduling and escalation policies","Integrates with 700+ monitoring and DevOps tools"]', '["Can be expensive for larger teams","Alert fatigue possible without proper configuration","Steep learning curve for advanced automation features"]', '["DevOps teams managing production infrastructure","SRE teams needing reliable on-call management","Enterprises requiring structured incident response workflows"]', 'PagerDuty remains the industry standard for incident management, providing the reliability and integration depth that operations teams need to keep critical services running.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('attio', 'Attio', 'saas', 'CRM', 'Next-generation CRM with real-time data enrichment', 'Attio is a next-generation CRM that automatically enriches contact and company data in real-time. It features a flexible data model, powerful filtering and segmentation, automatic relationship mapping from email and calendar data, and an intuitive interface that adapts to different team workflows.', NULL, 'https://attio.com', 8.4, true, 29, 'USD', '{"auto_data_enrichment": true, "flexible_data_model": true, "relationship_mapping": true, "advanced_filtering": true, "workflow_automation": true}', '["Automatic data enrichment keeps records current","Beautifully designed, intuitive interface","Flexible enough for different team workflows","Relationship intelligence from email and calendar"]', '["Smaller integration library than HubSpot","Advanced automation on higher tiers only","Newer platform with less market validation"]', '["Startups wanting a modern CRM experience","Sales teams tired of manual data entry","Relationship-driven businesses needing smart CRM"]', 'Attio represents the next generation of CRM, combining automatic data enrichment with a beautiful interface that makes customer relationship management feel effortless.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('retool-workflows', 'Retool Workflows', 'saas', 'Business Automation', 'Visual workflow automation for internal operations', 'Retool Workflows provides visual, code-enhanced workflow automation for internal business operations. It connects to databases, APIs, and SaaS tools to automate complex multi-step processes with a visual builder that supports JavaScript, SQL, and Python for advanced logic, bridging the gap between no-code and full-code automation.', NULL, 'https://retool.com/products/workflows', 8.2, true, 10, 'USD', '{"visual_workflow_builder": true, "code_enhanced_automation": true, "database_connectors": true, "api_integrations": true, "scheduled_triggers": true}', '["Combines visual building with real code for flexibility","Direct database connections for complex operations","Scheduled and event-driven trigger options","Part of the broader Retool ecosystem"]', '["Requires some technical knowledge for advanced use","Pricing tied to Retool platform subscription","Less intuitive for non-technical users than Zapier"]', '["Engineering teams automating internal operations","Companies with complex workflows needing code flexibility","Teams already using Retool for internal tools"]', 'Retool Workflows fills the gap between simple no-code tools and custom development, offering visual automation enhanced with real code for teams that need more power than Zapier provides.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('dub', 'Dub', 'saas', 'Link Management', 'Open-source link management platform for modern marketing', 'Dub is an open-source link management platform that provides URL shortening, branded links, QR codes, and click analytics. It offers geographic and device-based analytics, custom domains, link expiration, and password protection, serving as a modern alternative to Bitly with self-hosting capability.', NULL, 'https://dub.co', 8.1, true, 24, 'USD', '{"branded_links": true, "click_analytics": true, "qr_codes": true, "custom_domains": true, "api_access": true}', '["Open-source with self-hosting option","Clean analytics dashboard","Custom domain support on all plans","Modern API for programmatic link management"]', '["Fewer enterprise features than Bitly","Self-hosting requires Next.js expertise","Smaller team and community than established competitors"]', '["Marketing teams needing branded link management","Developers wanting programmatic link shortening","Organizations preferring open-source link analytics"]', 'Dub is a modern, open-source link management platform that offers a compelling alternative to Bitly with clean analytics, branded links, and the option to self-host.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('erxes', 'Erxes', 'saas', 'Business Operating System', 'Open-source experience operating system for business', 'Erxes is an open-source experience operating system (XOS) that combines CRM, marketing automation, help desk, project management, and team collaboration in a single platform. It provides a plugin-based architecture where businesses can enable only the modules they need, from sales pipelines to customer support and marketing campaigns.', NULL, 'https://erxes.io', 7.5, true, 0, 'USD', '{"modular_architecture": true, "crm_module": true, "marketing_automation": true, "help_desk": true, "self_hosting": true}', '["Open-source all-in-one business platform","Modular design lets you use only what you need","Self-hosting provides complete data control","Combines CRM, marketing, and support in one"]', '["Each module less powerful than dedicated tools","Setup and configuration can be complex","Smaller community than individual tool alternatives"]', '["Small businesses wanting an all-in-one open-source platform","Organizations needing self-hosted CRM and marketing tools","Teams looking to reduce tool sprawl with a unified platform"]', 'Erxes offers an ambitious all-in-one open-source business platform that reduces tool sprawl, though individual modules may not match the depth of dedicated single-purpose solutions.', 'published');
