-- =============================================================================
-- 22-more-tools.sql
-- 50 NEW tools across 6 categories
-- Distribution: ai-tools +9, business +8, ecommerce +8, hosting +8, marketing +8, saas +9
-- Generated: 2026-03-05
-- =============================================================================

-- ---------------------------------------------------------------------------
-- AI-TOOLS (+9 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('google-veo', 'Google Veo', 'ai-tools', 'AI Video Generation', 'Google DeepMind''s state-of-the-art AI video generation model', 'Google Veo is an advanced AI video generation model developed by Google DeepMind that creates high-quality, realistic videos from text prompts and images. Available through Google AI Studio and Vertex AI, Veo produces cinematic-quality clips with accurate physics, natural motion, and consistent visual style across frames.', NULL, 'https://deepmind.google/technologies/veo/', 8.7, true, 0, 'USD', '{"text_to_video": true, "image_to_video": true, "high_resolution_output": true, "consistent_motion": true, "google_cloud_integration": true}', '["Produces remarkably realistic and coherent video","Excellent understanding of physics and natural motion","Integrated with Google AI Studio and Vertex AI","Free tier available for experimentation"]', '["Limited availability compared to consumer tools","Requires Google Cloud account for full access","Generation times can be slow for long clips"]', '["Content creators needing high-quality AI video","Marketing teams producing video ads at scale","Developers integrating video generation into applications"]', 'Google Veo represents the cutting edge of AI video generation, producing cinematic-quality output that rivals professional footage for short-form content creation.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('replit-ai', 'Replit AI', 'ai-tools', 'AI Development Environment', 'AI-powered cloud IDE for building and deploying software', 'Replit AI is a cloud-based development environment with deeply integrated AI capabilities. It features an AI coding assistant that can generate, explain, and debug code, plus Replit Agent that can build complete applications from natural language descriptions. It supports 50+ languages with instant deployment and multiplayer collaboration.', NULL, 'https://replit.com', 8.5, true, 25, 'USD', '{"ai_code_generation": true, "replit_agent": true, "cloud_ide": true, "instant_deployment": true, "multiplayer_coding": true}', '["Full cloud IDE with no local setup required","Replit Agent builds complete apps from descriptions","Instant deployment to production with one click","Multiplayer collaboration for pair programming"]', '["Performance can lag compared to local IDEs","Free tier has limited compute resources","AI suggestions occasionally miss project context"]', '["Students and beginners learning to code","Developers prototyping ideas quickly in the cloud","Teams wanting collaborative coding with AI assistance"]', 'Replit AI combines a powerful cloud IDE with genuinely useful AI coding capabilities, making it the fastest path from idea to deployed application for both beginners and experienced developers.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('openai-sora', 'OpenAI Sora', 'ai-tools', 'AI Video Generation', 'OpenAI''s text-to-video generation model for creative content', 'OpenAI Sora is a text-to-video AI model that generates realistic and imaginative video scenes from text descriptions. It can create videos up to a minute long while maintaining visual quality and adherence to the user''s prompt. Sora is available through ChatGPT Plus and Pro subscriptions and offers storyboard-based editing.', NULL, 'https://sora.com', 8.4, false, 20, 'USD', '{"text_to_video": true, "storyboard_editing": true, "video_remixing": true, "multiple_aspect_ratios": true, "hd_output": true}', '["Generates highly creative and visually impressive videos","Storyboard feature enables multi-scene narrative control","Available directly within the ChatGPT ecosystem","Strong adherence to complex text prompts"]', '["Requires ChatGPT Plus or Pro subscription","Generation limits vary by subscription tier","Cannot reliably render text or complex human hands"]', '["Creative professionals exploring AI-generated video","Social media creators producing short-form content","Marketing teams prototyping video concepts quickly"]', 'OpenAI Sora pushes the boundaries of text-to-video generation with impressive creative capabilities, though it works best as a rapid prototyping tool rather than a production video replacement.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('hugging-face', 'Hugging Face', 'ai-tools', 'AI Model Hub & Platform', 'The open-source platform for machine learning models and datasets', 'Hugging Face is the leading open-source platform for sharing, discovering, and deploying machine learning models. It hosts over 500,000 models and 100,000 datasets, provides the Transformers library for Python, offers inference endpoints for model deployment, and enables collaborative model development through its Git-based hub.', NULL, 'https://huggingface.co', 9.2, true, 0, 'USD', '{"model_hub": true, "datasets_library": true, "inference_endpoints": true, "spaces_for_demos": true, "transformers_library": true}', '["Largest open-source ML model repository in the world","Transformers library is industry standard for NLP","Free hosting for model demos via Spaces","Active community with extensive documentation"]', '["Inference endpoints pricing can add up at scale","Platform can be overwhelming for beginners","Model quality varies widely across community uploads"]', '["ML engineers and researchers sharing and finding models","Data scientists building NLP and computer vision applications","Companies deploying open-source AI models to production"]', 'Hugging Face is the undisputed hub of the open-source AI ecosystem, providing essential infrastructure for discovering, sharing, and deploying machine learning models at any scale.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('replicate', 'Replicate', 'ai-tools', 'AI Model Deployment', 'Run open-source AI models in the cloud with a simple API', 'Replicate is a platform for running open-source machine learning models in the cloud via a simple API. It hosts thousands of models for image generation, language processing, audio, and video, allowing developers to integrate AI capabilities into applications without managing GPU infrastructure or model deployment.', NULL, 'https://replicate.com', 8.3, true, 0, 'USD', '{"api_access": true, "thousands_of_models": true, "pay_per_use": true, "custom_model_hosting": true, "streaming_output": true}', '["Extremely simple API for running any hosted model","Pay-per-use pricing with no minimum commitment","Thousands of open-source models ready to use","Supports custom model deployment via Cog"]', '["Cold start latency for less popular models","Per-prediction costs add up at high volume","Less control than self-hosted infrastructure"]', '["Developers integrating AI into applications quickly","Startups prototyping AI features without infrastructure","Teams wanting to test multiple models before committing"]', 'Replicate makes running open-source AI models as simple as an API call, offering an excellent balance of ease-of-use and model variety for developers building AI-powered applications.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('notion-ai-assistant', 'Notion AI', 'ai-tools', 'AI Writing & Productivity', 'AI assistant integrated into Notion for writing and knowledge work', 'Notion AI is an integrated AI assistant within Notion that helps with writing, summarizing, brainstorming, and extracting insights from your workspace. It can draft documents, translate content, fix grammar, generate action items from meetings, answer questions about your notes, and automate repetitive tasks across your Notion workspace.', NULL, 'https://notion.so/product/ai', 8.1, false, 10, 'USD', '{"ai_writing_assistant": true, "document_summarization": true, "q_and_a_from_workspace": true, "translation": true, "autofill_databases": true}', '["Deeply integrated into the Notion workflow","Can answer questions from your entire workspace","Autofill database properties save significant time","Natural language to database query is powerful"]', '["Requires Notion subscription plus AI add-on","AI quality varies for complex or niche tasks","Cannot access data outside your Notion workspace"]', '["Notion power users wanting AI-enhanced productivity","Teams with extensive Notion knowledge bases","Writers and content creators working within Notion"]', 'Notion AI is most valuable for teams already invested in Notion, providing contextual AI assistance that leverages your existing workspace knowledge in ways standalone AI tools cannot.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('together-ai', 'Together AI', 'ai-tools', 'AI Model Inference', 'Fast and affordable inference platform for open-source AI models', 'Together AI provides a high-performance inference platform for running open-source large language models, image models, and embedding models. It offers the fastest inference speeds for models like Llama, Mistral, and SDXL, with competitive pricing, fine-tuning capabilities, and an OpenAI-compatible API for easy migration.', NULL, 'https://together.ai', 8.4, true, 0, 'USD', '{"fast_inference": true, "openai_compatible_api": true, "model_fine_tuning": true, "dedicated_endpoints": true, "embedding_models": true}', '["Industry-leading inference speed for open-source models","OpenAI-compatible API simplifies migration","Competitive per-token pricing","Fine-tuning available for custom models"]', '["Model selection limited to open-source ecosystem","Documentation can lag behind feature releases","Enterprise support requires custom pricing"]', '["Developers building applications with open-source LLMs","Companies wanting faster or cheaper alternatives to OpenAI","ML teams fine-tuning open-source models for production"]', 'Together AI offers the fastest and most cost-effective way to run open-source AI models in production, with an API design that makes switching from OpenAI nearly effortless.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('tldraw', 'tldraw', 'ai-tools', 'AI Design & Whiteboard', 'Open-source collaborative whiteboard with AI-powered features', 'tldraw is an open-source collaborative whiteboard and drawing tool that includes AI-powered features for turning sketches into functional UI components and code. Its Make Real feature uses AI to convert hand-drawn wireframes into working HTML, while the core whiteboard supports real-time collaboration, shapes, arrows, and freehand drawing.', NULL, 'https://tldraw.com', 7.9, true, 0, 'USD', '{"collaborative_whiteboard": true, "ai_sketch_to_code": true, "real_time_collaboration": true, "open_source": true, "embeddable_component": true}', '["Open-source and free to use","Make Real converts sketches to working code","Smooth and responsive drawing experience","Can be embedded into other applications"]', '["AI features are experimental and not always accurate","Fewer built-in shapes than professional diagram tools","Make Real requires OpenAI API key for self-hosted use"]', '["Designers sketching quick ideas collaboratively","Developers prototyping UI from hand-drawn wireframes","Teams wanting an open-source Figma whiteboard alternative"]', 'tldraw combines a delightful open-source whiteboard experience with experimental AI features that hint at the future of design-to-code workflows.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('pieces-for-developers', 'Pieces for Developers', 'ai-tools', 'AI Developer Productivity', 'AI-powered code snippet manager and developer copilot', 'Pieces for Developers is an AI-powered productivity tool that captures, organizes, and enriches code snippets and development context. It provides a personal AI copilot that understands your workflow, saves and retrieves code snippets with rich context, and integrates with IDEs, browsers, and collaboration tools to reduce context switching.', NULL, 'https://pieces.app', 7.8, true, 0, 'USD', '{"ai_code_snippets": true, "context_aware_copilot": true, "multi_ide_support": true, "browser_extension": true, "on_device_ai": true}', '["On-device AI means code never leaves your machine","Captures code context automatically","Works across IDE, browser, and collaboration tools","Generous free tier with core features"]', '["Less well-known than GitHub Copilot","On-device AI requires decent hardware","Snippet organization can feel overwhelming initially"]', '["Developers who frequently reuse code snippets","Teams wanting on-device AI for privacy","Developers who context-switch between many projects"]', 'Pieces for Developers is a thoughtful productivity tool that solves the real problem of losing code context and snippets across tools, with on-device AI that respects privacy.', 'published');

-- ---------------------------------------------------------------------------
-- BUSINESS (+8 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('fellow', 'Fellow', 'business', 'Meeting Management', 'AI-powered meeting management platform for productive teams', 'Fellow is an AI-powered meeting management platform that helps teams run effective meetings with collaborative agendas, real-time note-taking, action item tracking, and AI-generated meeting summaries. It integrates with calendars, video conferencing, and project management tools to ensure every meeting produces clear outcomes and accountability.', NULL, 'https://fellow.app', 8.2, true, 7, 'USD', '{"collaborative_agendas": true, "ai_meeting_summaries": true, "action_item_tracking": true, "meeting_templates": true, "one_on_one_tools": true}', '["AI summaries and transcription save post-meeting time","Collaborative agendas keep meetings focused","Action items integrate with project management tools","Strong 1-on-1 meeting features for managers"]', '["Free tier limited in AI features","Requires team adoption to be most effective","Advanced analytics on higher plans only"]', '["Managers running regular 1-on-1 meetings","Teams wanting structured and accountable meetings","Organizations looking to reduce unproductive meeting time"]', 'Fellow transforms meetings from time drains into productive sessions with structured agendas and AI-powered summaries that ensure nothing falls through the cracks.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('trainual', 'Trainual', 'business', 'Training & Onboarding', 'Knowledge transfer and training platform for growing teams', 'Trainual is a training and onboarding platform that helps businesses document processes, create training content, and ensure consistent knowledge transfer across teams. It features role-based training assignments, progress tracking, built-in screen recording, quizzes, and a searchable knowledge base that becomes the single source of truth for how things are done.', NULL, 'https://trainual.com', 8.1, false, 250, 'USD', '{"role_based_training": true, "progress_tracking": true, "screen_recording": true, "quizzes_and_tests": true, "searchable_knowledge_base": true}', '["Makes onboarding new hires systematic and consistent","Role-based assignments ensure relevant training","Built-in screen recording for easy content creation","Searchable knowledge base for ongoing reference"]', '["Starting price of $250/month is steep for small teams","Content creation requires upfront time investment","Limited customization for enterprise branding"]', '["Growing companies standardizing employee onboarding","Franchise businesses ensuring consistent operations","HR teams building scalable training programs"]', 'Trainual is the best platform for businesses that need to systematize knowledge transfer and onboarding, ensuring every team member learns the right processes for their role.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('calendly-routing', 'Calendly', 'business', 'Scheduling Automation', 'Automated scheduling platform that eliminates back-and-forth emails', 'Calendly is a scheduling automation platform that eliminates the back-and-forth of finding meeting times. It allows professionals to share booking links, set availability rules, route meetings to the right team members, collect payments, and integrate with calendars, video conferencing, and CRM tools for seamless scheduling workflows.', NULL, 'https://calendly.com', 8.8, true, 10, 'USD', '{"booking_links": true, "team_scheduling": true, "routing_forms": true, "payment_collection": true, "calendar_integrations": true}', '["Extremely easy to set up and share booking links","Team scheduling with round-robin and routing","Integrates with all major calendar and video tools","Reduces scheduling friction dramatically"]', '["Advanced routing requires higher-tier plans","Can feel impersonal for some client relationships","Limited customization on lower tiers"]', '["Sales teams automating prospect meeting bookings","Consultants and freelancers managing client scheduling","Teams reducing internal scheduling overhead"]', 'Calendly remains the gold standard for scheduling automation, offering a frictionless booking experience that saves hours of email back-and-forth for professionals and teams.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('lucidchart', 'Lucidchart', 'business', 'Diagramming & Visualization', 'Intelligent diagramming platform for teams', 'Lucidchart is a cloud-based intelligent diagramming platform that helps teams visualize complex systems, processes, and organizational structures. It supports flowcharts, network diagrams, UML, ERDs, org charts, and more with real-time collaboration, automated diagramming from data imports, and extensive template and shape libraries.', NULL, 'https://lucidchart.com', 8.7, true, 8, 'USD', '{"intelligent_diagramming": true, "real_time_collaboration": true, "data_import_automation": true, "extensive_templates": true, "integrations": true}', '["Industry-leading diagramming capability and shape library","Auto-generate diagrams from CSV, Visio, and cloud data","Real-time collaboration with commenting","Integrates with Google Workspace, Atlassian, and Slack"]', '["Free tier is quite limited in shapes and documents","Premium features require Team or Business plans","Can feel heavy for simple diagrams"]', '["IT teams documenting network and system architecture","Business analysts creating process flow documentation","Engineering teams building technical diagrams collaboratively"]', 'Lucidchart is the most powerful and versatile cloud diagramming platform available, offering enterprise-grade capabilities that make it essential for teams documenting complex systems and processes.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('mixmax', 'Mixmax', 'business', 'Email Productivity', 'Email productivity and engagement platform for revenue teams', 'Mixmax is an email productivity platform that enhances Gmail with scheduling, email tracking, sequences, templates, polls, and CRM integration. It helps sales and customer success teams automate email outreach, track engagement, and book meetings directly from email without leaving the Gmail interface.', NULL, 'https://mixmax.com', 7.9, true, 29, 'USD', '{"email_tracking": true, "sequences": true, "meeting_scheduler": true, "email_templates": true, "crm_integration": true}', '["Enhances Gmail without requiring a separate platform","Email tracking and real-time notifications","One-click meeting scheduling in emails","Sequences automate multi-step outreach"]', '["Only works with Gmail, not Outlook","Higher pricing compared to basic email tools","Some features overlap with CRM capabilities"]', '["Sales teams using Gmail for outbound outreach","Account executives managing pipeline from inbox","Customer success teams needing email engagement tracking"]', 'Mixmax is the best email productivity enhancement for Gmail-based sales teams, providing tracking, sequences, and scheduling without the complexity of a full sales engagement platform.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('reclaim-ai', 'Reclaim.ai', 'business', 'Smart Calendar Management', 'AI scheduling assistant that protects time for what matters', 'Reclaim.ai is an AI-powered scheduling assistant that automatically finds the best time for habits, tasks, meetings, and breaks in your calendar. It defends focus time, schedules recurring routines, integrates tasks from project management tools, and provides team-wide scheduling analytics to combat meeting overload and burnout.', NULL, 'https://reclaim.ai', 8.3, true, 8, 'USD', '{"smart_scheduling": true, "habit_protection": true, "task_integration": true, "team_analytics": true, "buffer_time": true}', '["AI protects focus time and personal habits automatically","Pulls tasks from Asana, Todoist, Jira, and ClickUp","Smart 1-on-1 scheduling finds mutual availability","Free tier includes core scheduling features"]', '["Google Calendar only, no Outlook support","AI scheduling decisions need occasional overrides","Advanced team features require paid plans"]', '["Knowledge workers wanting protected deep work time","Managers scheduling 1-on-1s across large teams","Professionals balancing meetings with heads-down work"]', 'Reclaim.ai is the smartest calendar assistant for professionals drowning in meetings, automatically defending the time needed for focused work, habits, and personal priorities.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('sunsama', 'Sunsama', 'business', 'Daily Planner', 'Calm daily planner for professionals who want intentional workdays', 'Sunsama is a daily planning tool that helps professionals create intentional workdays by pulling tasks from Asana, Trello, Jira, Linear, GitHub, Gmail, and Slack into a unified daily plan. It encourages time-boxing, daily planning rituals, and work-life balance with guided shutdown routines and weekly reviews.', NULL, 'https://sunsama.com', 8.2, false, 16, 'USD', '{"daily_planning_ritual": true, "task_import_integrations": true, "time_boxing": true, "shutdown_routine": true, "weekly_review": true}', '["Guided daily planning ritual promotes intentionality","Imports tasks from 10+ project management tools","Time-boxing encourages realistic workload planning","Shutdown routine supports work-life balance"]', '["No free tier available","Single-purpose tool with focused scope","Requires discipline to use the planning ritual daily"]', '["Knowledge workers overwhelmed by scattered tasks","Professionals wanting a calmer daily planning approach","Managers balancing tasks across multiple project tools"]', 'Sunsama is uniquely focused on making each workday intentional and manageable, providing a calming daily planning experience that stands apart from traditional task management tools.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('pitch', 'Pitch', 'business', 'Presentation Software', 'Modern collaborative presentation software for teams', 'Pitch is a modern presentation platform designed for team collaboration. It features a sleek editor with smart formatting, brand-consistent templates, real-time collaboration, video recording within slides, presentation analytics, and AI-powered content generation for creating professional decks faster than traditional tools.', NULL, 'https://pitch.com', 8.1, true, 8, 'USD', '{"collaborative_editor": true, "brand_templates": true, "video_in_slides": true, "presentation_analytics": true, "ai_content_generation": true}', '["Beautiful design with smart auto-formatting","Real-time collaboration better than PowerPoint","Record video directly within presentations","Analytics show how viewers engage with decks"]', '["Smaller template library than Canva","Export to PowerPoint can lose some formatting","Advanced features need paid plans"]', '["Startup teams creating investor pitch decks","Marketing teams building brand-consistent presentations","Sales teams tracking how prospects engage with decks"]', 'Pitch modernizes presentation creation with beautiful defaults, seamless collaboration, and engagement analytics that make it the strongest team presentation tool available today.', 'published');

-- ---------------------------------------------------------------------------
-- ECOMMERCE (+8 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('fourthwall', 'Fourthwall', 'ecommerce', 'Creator Commerce Platform', 'All-in-one commerce platform for creators and influencers', 'Fourthwall is a commerce platform built specifically for content creators and influencers. It combines a customizable storefront, merchandise production, membership subscriptions, and digital product sales with integrations for YouTube, Twitch, and TikTok. Creators can sell custom merch, offer exclusive memberships, and manage their entire business from one platform.', NULL, 'https://fourthwall.com', 8.4, true, 0, 'USD', '{"custom_storefronts": true, "merch_production": true, "membership_subscriptions": true, "creator_integrations": true, "digital_products": true}', '["Purpose-built for content creators","No monthly fees, only per-transaction costs","Merch production with no minimum orders","YouTube, Twitch, and TikTok integrations"]', '["Less flexible than general ecommerce platforms","Merch quality and selection varies","Limited SEO tools for organic discovery"]', '["YouTubers and streamers selling merchandise","Content creators offering paid memberships","Influencers wanting an all-in-one commerce solution"]', 'Fourthwall is the best commerce platform specifically built for creators, combining merch, memberships, and digital products with the creator platform integrations that matter most.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('shopify-markets', 'Shopify Markets', 'ecommerce', 'Cross-Border Commerce', 'Sell internationally from a single Shopify store with localized experiences', 'Shopify Markets is Shopify''s built-in cross-border commerce solution that enables merchants to sell internationally from a single store. It provides automatic currency conversion, localized languages, regional pricing strategies, duties and import tax calculation, and market-specific domains to create native shopping experiences for customers worldwide.', NULL, 'https://shopify.com/markets', 8.6, false, 39, 'USD', '{"multi_currency": true, "language_localization": true, "duties_and_taxes": true, "regional_pricing": true, "market_specific_domains": true}', '["Manage international sales from one store","Automatic duties and tax calculation at checkout","Localized currencies and languages","Built into Shopify with no additional apps needed"]', '["Requires Shopify subscription as prerequisite","Advanced Markets Pro features cost extra","Not all payment methods available in all regions"]', '["Shopify merchants expanding internationally","DTC brands selling cross-border","Ecommerce businesses wanting localized shopping experiences"]', 'Shopify Markets makes international selling remarkably simple for Shopify merchants, handling the complexity of currencies, taxes, and localization that previously required multiple third-party apps.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('junip', 'Junip', 'ecommerce', 'Product Reviews', 'Beautiful product review platform for Shopify and headless stores', 'Junip is a product review platform that helps ecommerce brands collect, display, and leverage customer reviews and user-generated content. It features customizable review widgets, photo and video reviews, automated review request flows, Google Shopping integration, and a modern design that matches premium brand aesthetics.', NULL, 'https://junip.co', 8.0, true, 19, 'USD', '{"review_collection": true, "photo_video_reviews": true, "google_shopping_integration": true, "customizable_widgets": true, "automated_requests": true}', '["Beautiful, modern review widgets that match premium brands","Photo and video review collection","Google Shopping rich snippet integration","Automated review request email flows"]', '["Limited to Shopify and headless stores","Fewer features than Judge.me or Yotpo","Advanced analytics require higher plans"]', '["Premium DTC brands wanting beautiful review displays","Shopify Plus stores needing Google Shopping reviews","Brands prioritizing UGC and visual social proof"]', 'Junip is the best choice for premium ecommerce brands that want review widgets matching their design standards, with solid review collection and Google Shopping integration.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('rebuy', 'Rebuy', 'ecommerce', 'Personalization Engine', 'AI-powered personalization and merchandising for Shopify stores', 'Rebuy is an AI-powered personalization platform for Shopify that delivers intelligent product recommendations, smart search, dynamic bundles, and personalized checkout experiences. It uses machine learning to analyze shopper behavior and automatically display the right products to each customer, increasing average order value and conversion rates.', NULL, 'https://rebuyengine.com', 8.5, true, 99, 'USD', '{"ai_recommendations": true, "smart_search": true, "dynamic_bundles": true, "personalized_checkout": true, "ab_testing": true}', '["AI recommendations measurably increase AOV","Smart search improves product discovery","Dynamic bundles drive upsell and cross-sell","Deep Shopify integration with easy setup"]', '["Starting at $99/month is steep for small stores","Shopify-only platform","Full personalization requires significant traffic data"]', '["Shopify stores focused on increasing AOV","DTC brands wanting AI-powered merchandising","High-traffic stores that benefit from personalization"]', 'Rebuy delivers measurable revenue lift through AI-powered personalization, making it a strong investment for Shopify stores with enough traffic to benefit from intelligent product recommendations.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('zettle', 'Zettle by PayPal', 'ecommerce', 'Point of Sale', 'Mobile point-of-sale system by PayPal for small businesses', 'Zettle by PayPal is a mobile point-of-sale (POS) system that enables small businesses to accept card payments, manage inventory, and track sales. It offers card readers, a free POS app, sales reporting, and integration with PayPal''s payment ecosystem, making it easy for small retailers, market vendors, and service providers to accept payments anywhere.', NULL, 'https://zettle.com', 7.8, true, 0, 'USD', '{"card_reader": true, "free_pos_app": true, "inventory_management": true, "sales_reporting": true, "paypal_integration": true}', '["No monthly fees for the POS app","Affordable card reader hardware","Seamless PayPal ecosystem integration","Simple setup for mobile and pop-up retail"]', '["Transaction fees higher than some competitors","Limited advanced POS features","Inventory management is basic compared to dedicated tools"]', '["Small retailers and market vendors accepting cards","Service providers needing mobile payment acceptance","PayPal users wanting integrated in-person payments"]', 'Zettle is an excellent entry-level POS for small businesses and mobile sellers who want simple, affordable card acceptance backed by PayPal''s trusted payment infrastructure.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('stamped-io', 'Stamped.io', 'ecommerce', 'Reviews & Loyalty', 'Product reviews and loyalty program platform for ecommerce', 'Stamped.io is an ecommerce platform combining product reviews, ratings, photo reviews, NPS surveys, and loyalty programs. It helps brands collect and display authentic customer reviews, create points-based loyalty programs, and leverage user-generated content to build trust and increase repeat purchases across Shopify, BigCommerce, and WooCommerce.', NULL, 'https://stamped.io', 8.1, true, 23, 'USD', '{"product_reviews": true, "loyalty_program": true, "photo_reviews": true, "nps_surveys": true, "multi_platform_support": true}', '["Combines reviews and loyalty in one platform","Works with Shopify, BigCommerce, and WooCommerce","Photo and video review collection","Affordable compared to Yotpo for similar features"]', '["Free tier is very limited","Loyalty features require separate subscription","Email design customization could be more flexible"]', '["Ecommerce brands wanting reviews plus loyalty in one tool","Shopify stores on a budget compared to Yotpo","Brands building customer retention through points programs"]', 'Stamped.io offers an excellent value proposition by combining reviews and loyalty into one platform, providing capabilities similar to Yotpo at a fraction of the price for growing ecommerce brands.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('shogun', 'Shogun', 'ecommerce', 'Ecommerce Page Builder', 'Visual page builder and storefront optimization for Shopify', 'Shogun is a visual page builder for ecommerce that enables merchants to create custom landing pages, product pages, and blog posts without coding. It features drag-and-drop editing, A/B testing, SEO tools, and Shogun Frontend for headless commerce, helping brands optimize their storefront experience and conversion rates.', NULL, 'https://getshogun.com', 8.0, false, 39, 'USD', '{"visual_page_builder": true, "ab_testing": true, "seo_optimization": true, "custom_elements": true, "headless_frontend": true}', '["Intuitive drag-and-drop page builder","Built-in A/B testing for conversion optimization","SEO tools for page-level optimization","Headless frontend option via Shogun Frontend"]', '["Monthly cost adds to overall tech stack expenses","Can slow page load if elements are not optimized","No free tier available"]', '["Shopify stores needing custom landing pages","Ecommerce marketers running conversion experiments","Brands wanting a headless frontend without building from scratch"]', 'Shogun is the leading ecommerce page builder for merchants who need custom landing pages and conversion testing without developer resources, with an optional headless frontend for advanced teams.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('loop-returns', 'Loop Returns', 'ecommerce', 'Returns Management', 'Automated returns and exchanges platform for Shopify brands', 'Loop Returns is a returns management platform that automates the returns and exchange process for Shopify brands. It encourages exchanges over refunds through intelligent product suggestions, offers bonus credit incentives, provides branded return portals, and integrates with shipping carriers for automated label generation and tracking.', NULL, 'https://loopreturns.com', 8.3, false, 59, 'USD', '{"automated_returns": true, "exchange_encouragement": true, "bonus_credit": true, "branded_portal": true, "carrier_integration": true}', '["Converts returns into exchanges, retaining revenue","Branded return portal matches store design","Automated label generation and tracking","Analytics reveal return patterns and reasons"]', '["Shopify-only platform","Starting price of $59/month may be high for small stores","Setup requires some configuration time"]', '["Shopify brands with high return volumes","DTC brands wanting to retain revenue from returns","Fashion and apparel stores where exchanges are common"]', 'Loop Returns transforms the returns process from a cost center into a revenue retention opportunity, making it essential for Shopify brands where returns and exchanges are a significant part of operations.', 'published');

-- ---------------------------------------------------------------------------
-- HOSTING (+8 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('supabase', 'Supabase', 'hosting', 'Backend-as-a-Service', 'Open-source Firebase alternative with Postgres database', 'Supabase is an open-source Backend-as-a-Service (BaaS) built on PostgreSQL that provides database hosting, authentication, instant APIs, edge functions, real-time subscriptions, and file storage. It offers a Firebase-like developer experience with the power and reliability of PostgreSQL, supporting self-hosting and a generous free tier.', NULL, 'https://supabase.com', 9.0, true, 25, 'USD', '{"postgres_database": true, "authentication": true, "instant_apis": true, "edge_functions": true, "realtime_subscriptions": true}', '["Built on PostgreSQL for reliability and SQL power","Generous free tier for development and small projects","Open-source with self-hosting option","Instant REST and GraphQL APIs from database schema"]', '["Free tier database pauses after inactivity","Edge functions ecosystem still maturing","Complex queries may need direct SQL knowledge"]', '["Full-stack developers needing a backend quickly","Startups building MVPs with limited backend resources","Teams wanting an open-source Firebase alternative"]', 'Supabase has become the go-to backend platform for modern web development, offering PostgreSQL reliability with a developer experience that makes Firebase users feel right at home.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('planetscale', 'PlanetScale', 'hosting', 'Serverless Database', 'Serverless MySQL-compatible database platform with branching', 'PlanetScale is a serverless database platform built on Vitess, the MySQL-compatible database system that powers YouTube. It offers database branching for schema migrations, non-blocking schema changes, read replicas, connection pooling, and automatic scaling, designed for teams that need a production-ready MySQL database without operational overhead.', NULL, 'https://planetscale.com', 8.6, true, 39, 'USD', '{"database_branching": true, "non_blocking_schema_changes": true, "serverless_scaling": true, "read_replicas": true, "connection_pooling": true}', '["Database branching makes schema changes safe","Non-blocking migrations avoid production downtime","Built on Vitess, proven at YouTube scale","Serverless scaling handles traffic spikes automatically"]', '["Free tier was recently removed (now Hobby tier)","No foreign key constraint support by default","MySQL-only, no PostgreSQL option"]', '["Teams needing safe, non-blocking schema migrations","Applications requiring serverless database scaling","Developers who want Git-like workflow for databases"]', 'PlanetScale brings a revolutionary branching workflow to database management, making schema changes as safe and reviewable as code changes for teams running MySQL at scale.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('neon', 'Neon', 'hosting', 'Serverless PostgreSQL', 'Serverless PostgreSQL with branching and autoscaling', 'Neon is a serverless PostgreSQL platform that separates storage and compute to enable features like database branching, autoscaling to zero, and instant read replicas. It provides a fully managed PostgreSQL experience with a generous free tier, making it ideal for modern applications that need PostgreSQL without managing infrastructure.', NULL, 'https://neon.tech', 8.7, true, 19, 'USD', '{"serverless_postgres": true, "database_branching": true, "autoscale_to_zero": true, "instant_read_replicas": true, "generous_free_tier": true}', '["Scale to zero means you pay nothing when idle","Database branching for safe development workflows","Generous free tier with 0.5 GB storage","True serverless PostgreSQL with instant provisioning"]', '["Cold starts when scaling from zero","Connection pooling needed for serverless frameworks","Storage costs can grow with branching"]', '["Serverless and JAMstack application developers","Startups wanting managed PostgreSQL with low initial costs","Teams needing database branching for development workflows"]', 'Neon is redefining PostgreSQL hosting with serverless architecture that scales to zero, offering the most cost-effective way to run PostgreSQL for modern applications with variable workloads.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('upstash', 'Upstash', 'hosting', 'Serverless Data Platform', 'Serverless Redis, Kafka, and QStash for modern applications', 'Upstash provides serverless Redis, Kafka, and QStash (HTTP-based message queue) with per-request pricing. It is designed for edge and serverless environments where traditional always-on databases are inefficient, offering low-latency global data access with automatic scaling and a generous free tier for development.', NULL, 'https://upstash.com', 8.3, true, 0, 'USD', '{"serverless_redis": true, "serverless_kafka": true, "qstash_messaging": true, "per_request_pricing": true, "global_replication": true}', '["True pay-per-request pricing with no minimum","Serverless Redis and Kafka purpose-built for edge","Generous free tier for development","Global replication for low-latency access"]', '["Performance slightly below dedicated Redis instances","Advanced Redis features may have limitations","Kafka throughput limited compared to managed clusters"]', '["Serverless and edge application developers","Vercel and Cloudflare Workers projects needing data stores","Teams wanting Redis or Kafka without server management"]', 'Upstash is the definitive serverless data platform for edge computing, providing Redis and Kafka with per-request pricing that makes it the most cost-efficient option for serverless architectures.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('deno-deploy', 'Deno Deploy', 'hosting', 'Edge Runtime Platform', 'Global edge runtime for JavaScript and TypeScript applications', 'Deno Deploy is a globally distributed edge runtime platform for JavaScript and TypeScript applications. Built on the Deno runtime, it deploys code to 35+ edge locations worldwide with zero configuration, supporting modern web standards, npm packages, and frameworks like Fresh and Hono with sub-millisecond cold starts.', NULL, 'https://deno.com/deploy', 8.2, true, 20, 'USD', '{"edge_deployment": true, "zero_config": true, "npm_compatibility": true, "kv_storage": true, "cron_jobs": true}', '["Deploys to 35+ edge locations globally","Zero-configuration deployment from Git","Sub-millisecond cold starts","Built-in KV storage for persistent data"]', '["Smaller ecosystem than Node.js/Vercel","Some npm packages have compatibility issues","Deno-specific APIs have a learning curve"]', '["Developers building edge-first web applications","Teams using TypeScript-heavy stacks","Projects needing globally distributed low-latency APIs"]', 'Deno Deploy offers the fastest path to globally distributed edge applications, combining the modern Deno runtime with zero-config deployment and built-in persistent storage.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('coolify', 'Coolify', 'hosting', 'Self-Hosted PaaS', 'Open-source self-hosted alternative to Heroku and Netlify', 'Coolify is an open-source, self-hosted Platform-as-a-Service (PaaS) that lets you deploy applications, databases, and services on your own servers. It supports Docker, Git-based deployments, automatic SSL, and one-click service installation, providing a Heroku-like experience on any VPS without vendor lock-in or platform fees.', NULL, 'https://coolify.io', 8.4, true, 0, 'USD', '{"self_hosted_paas": true, "docker_support": true, "git_deployments": true, "automatic_ssl": true, "one_click_services": true}', '["Completely free and open-source","Deploy on any VPS or server you own","Heroku-like experience without platform costs","One-click deployment of databases and services"]', '["Requires server administration knowledge","Single-server default limits high availability","Smaller community than established PaaS platforms"]', '["Developers wanting Heroku-like experience on their own servers","Teams escaping platform lock-in and rising PaaS costs","Self-hosters wanting a modern deployment platform"]', 'Coolify is the most polished open-source PaaS available, giving developers the convenience of Heroku on their own infrastructure without recurring platform fees.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('turso', 'Turso', 'hosting', 'Edge Database', 'SQLite-based distributed database for edge applications', 'Turso is a distributed database built on libSQL, an open-source fork of SQLite. It replicates data to edge locations worldwide for ultra-low latency reads, supports embedded replicas within applications, and provides a familiar SQLite interface with the scalability of a distributed system, perfect for edge-first and local-first applications.', NULL, 'https://turso.tech', 8.1, true, 0, 'USD', '{"edge_replication": true, "embedded_replicas": true, "libsql_based": true, "branching": true, "generous_free_tier": true}', '["SQLite simplicity with distributed edge replication","Embedded replicas bring data into your application","Generous free tier with 9 GB storage","Extremely low-latency reads at the edge"]', '["Write operations limited to primary region","SQLite limitations apply for complex queries","Newer platform with smaller community"]', '["Edge application developers needing local-fast reads","Local-first application architectures","Developers who love SQLite but need distribution"]', 'Turso brings SQLite to the edge with a unique embedded replica model that delivers near-zero latency reads, making it ideal for the growing local-first and edge-first application movement.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('dokku', 'Dokku', 'hosting', 'Self-Hosted PaaS', 'The smallest PaaS implementation you have ever seen', 'Dokku is a lightweight, open-source PaaS built on Docker that provides Heroku-like deployment workflows on a single server. It supports Heroku buildpacks, Dockerfile deployments, automatic SSL via Let''s Encrypt, persistent storage, and a plugin system for databases, caching, and other services, all managed through simple Git push commands.', NULL, 'https://dokku.com', 8.0, true, 0, 'USD', '{"git_push_deployment": true, "heroku_buildpacks": true, "dockerfile_support": true, "automatic_ssl": true, "plugin_ecosystem": true}', '["Extremely lightweight and easy to set up","Familiar Heroku-style git push workflow","Active plugin ecosystem for databases and services","Completely free and open-source"]', '["Single-server architecture limits scaling","Requires command-line comfort for management","No built-in web dashboard","Documentation can be sparse for edge cases"]', '["Solo developers deploying side projects","Teams wanting Heroku workflow on a cheap VPS","Developers learning deployment and DevOps concepts"]', 'Dokku is the original self-hosted PaaS that proves you do not need expensive platforms for Heroku-style deployments, perfect for developers who want simplicity on a single server.', 'published');

-- ---------------------------------------------------------------------------
-- MARKETING (+8 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('lemlist', 'Lemlist', 'marketing', 'Cold Outreach & Email', 'Multichannel outreach platform with personalized email sequences', 'Lemlist is a multichannel outreach platform that combines personalized cold email, LinkedIn outreach, and phone calls into automated sequences. It features AI-generated personalized images, custom landing pages, email warmup, lead enrichment, and deliverability monitoring to help sales teams run effective outbound campaigns at scale.', NULL, 'https://lemlist.com', 8.4, false, 39, 'USD', '{"multichannel_sequences": true, "personalized_images": true, "email_warmup": true, "lead_enrichment": true, "deliverability_monitoring": true}', '["Unique personalized image and video features","Multichannel sequences across email, LinkedIn, and phone","Built-in email warmup tool","Strong deliverability monitoring and optimization"]', '["No free tier available","Pricing per seat adds up for larger teams","Learning curve for advanced personalization features"]', '["Sales teams running multichannel outbound campaigns","B2B companies needing personalized cold outreach","Agencies managing outreach for multiple clients"]', 'Lemlist stands out in the crowded outreach market with its unique personalization capabilities, combining email, LinkedIn, and phone into truly multichannel campaigns that feel personal at scale.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('clay', 'Clay', 'marketing', 'Data Enrichment & Outreach', 'Waterfall data enrichment platform for go-to-market teams', 'Clay is a data enrichment and outreach platform that uses a waterfall approach across 75+ data providers to find the best contact and company information. It features a spreadsheet-like interface with AI-powered research agents, automated enrichment workflows, and integrations with CRMs and outreach tools to build hyper-personalized campaigns.', NULL, 'https://clay.com', 8.8, true, 149, 'USD', '{"waterfall_enrichment": true, "75_plus_data_providers": true, "ai_research_agents": true, "spreadsheet_interface": true, "crm_integrations": true}', '["Waterfall enrichment finds data other tools miss","AI agents automate prospect research","Spreadsheet interface is intuitive for GTM teams","Integrates with every major CRM and outreach tool"]', '["Premium pricing starting at $149/month","Credits system requires monitoring usage","Steep learning curve for advanced workflows"]', '["Go-to-market teams building targeted prospect lists","Sales ops teams enriching CRM data at scale","Revenue teams personalizing outreach with deep research"]', 'Clay has become the essential data enrichment tool for modern go-to-market teams, with its waterfall approach and AI agents producing richer prospect data than any single data provider can offer.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('sprig', 'Sprig', 'marketing', 'Product Experience Insights', 'AI-powered product experience platform with in-product surveys', 'Sprig is a product experience platform that helps teams understand user behavior through in-product surveys, session replays, and AI-powered analysis. It captures user feedback at the moment of experience, records sessions with event-based triggers, and uses AI to identify patterns and recommend product improvements automatically.', NULL, 'https://sprig.com', 8.2, true, 0, 'USD', '{"in_product_surveys": true, "session_replays": true, "ai_analysis": true, "heatmaps": true, "user_targeting": true}', '["In-context surveys capture feedback at the right moment","AI automatically identifies patterns in user feedback","Session replays show exactly what users experience","Targeted surveys based on user behavior and attributes"]', '["Advanced features require paid plans","Survey fatigue if not carefully managed","Smaller brand recognition than Hotjar or FullStory"]', '["Product teams wanting actionable user feedback","UX researchers conducting in-product studies","Growth teams optimizing user activation and retention"]', 'Sprig uniquely combines in-product surveys with session replays and AI analysis, providing product teams with the context they need to make confident product decisions.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('amplitude', 'Amplitude', 'marketing', 'Product Analytics', 'Digital analytics platform for understanding user behavior at scale', 'Amplitude is a digital analytics platform that helps product and growth teams understand user behavior, identify conversion opportunities, and measure the impact of product changes. It provides behavioral cohorts, funnel analysis, retention tracking, experiment analysis, and AI-powered insights for data-driven product decisions.', NULL, 'https://amplitude.com', 8.9, true, 0, 'USD', '{"behavioral_analytics": true, "funnel_analysis": true, "retention_tracking": true, "cohort_analysis": true, "experiment_tracking": true}', '["Industry-leading behavioral analytics depth","Generous free tier with 10M events/month","Powerful cohort and retention analysis","Strong integration ecosystem"]', '["Complex setup for advanced tracking plans","Learning curve for non-technical users","Enterprise pricing can be significant"]', '["Product teams making data-driven feature decisions","Growth teams analyzing user acquisition and retention","Companies needing deep behavioral analytics at scale"]', 'Amplitude is the gold standard for product analytics, offering unmatched depth in behavioral analysis that enables product teams to truly understand and optimize the user journey.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('customer-io-data-pipelines', 'Customer.io Data Pipelines', 'marketing', 'Customer Data Platform', 'Customer data platform for collecting and routing event data', 'Customer.io Data Pipelines (formerly Journeys) is a customer data platform that collects, unifies, and routes customer event data across your entire marketing and product stack. It serves as a Segment alternative, providing SDKs for data collection, identity resolution, audience building, and real-time data routing to 200+ downstream destinations.', NULL, 'https://customer.io/data-pipelines', 8.3, true, 0, 'USD', '{"event_collection": true, "identity_resolution": true, "audience_building": true, "data_routing": true, "200_plus_destinations": true}', '["Affordable alternative to Segment","Real-time data routing to 200+ tools","Strong identity resolution across devices","Generous free tier for startups"]', '["Less established than Segment in enterprise","Fewer native integrations than larger CDPs","Documentation can lag behind new features"]', '["Startups needing a CDP without Segment pricing","Marketing teams wanting unified customer data","Product teams routing events to multiple analytics tools"]', 'Customer.io Data Pipelines offers a compelling CDP alternative to Segment, providing essential data routing and identity resolution at a price point accessible to growing companies.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('mixpanel', 'Mixpanel', 'marketing', 'Product Analytics', 'Self-serve product analytics for understanding user engagement', 'Mixpanel is a product analytics platform that helps teams measure and improve user engagement through event-based tracking. It provides interactive reports for funnels, flows, retention, and segmentation, plus an intuitive query builder that enables non-technical teams to explore data and answer product questions without SQL knowledge.', NULL, 'https://mixpanel.com', 8.7, true, 0, 'USD', '{"event_analytics": true, "funnel_analysis": true, "flow_reports": true, "retention_analysis": true, "self_serve_exploration": true}', '["Intuitive self-serve interface for non-technical users","Powerful funnel and retention analysis","Generous free tier with 20M events/month","Interactive data exploration without SQL"]', '["Advanced features require Growth or Enterprise plans","Data governance requires careful tracking plan design","Can be expensive at high event volumes"]', '["Product managers tracking feature adoption and engagement","Growth teams analyzing conversion funnels","Teams wanting self-serve analytics without a data team"]', 'Mixpanel excels at making product analytics accessible to non-technical teams, with an intuitive interface that enables anyone to explore user behavior and find actionable insights.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('resend', 'Resend', 'marketing', 'Transactional Email', 'Modern email API for developers with React email support', 'Resend is a modern email API built for developers that makes sending transactional and marketing emails straightforward. It features a clean API, React Email for building email templates with components, domain authentication, email analytics, and webhooks. Designed as a developer-first alternative to SendGrid and Mailgun with better DX.', NULL, 'https://resend.com', 8.5, true, 0, 'USD', '{"email_api": true, "react_email_templates": true, "domain_authentication": true, "analytics_dashboard": true, "webhook_events": true}', '["Beautiful developer experience and documentation","React Email enables component-based email templates","Generous free tier with 3,000 emails/month","Simple pricing that scales predictably"]', '["Newer platform with less enterprise validation","Fewer features than SendGrid for complex use cases","Marketing email features still developing"]', '["Developers building transactional email systems","Teams using React who want component-based email templates","Startups wanting modern email infrastructure"]', 'Resend brings a refreshingly modern developer experience to email infrastructure, with React Email templates that make building beautiful transactional emails feel like building web components.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('segment', 'Segment', 'marketing', 'Customer Data Platform', 'The leading customer data platform for collecting and routing data', 'Segment is the leading customer data platform (CDP) that collects user events from websites, apps, and servers, then routes that data to hundreds of analytics, marketing, and data warehouse tools. It provides identity resolution, audience building, privacy controls, and a unified customer view that serves as the data foundation for the entire marketing stack.', NULL, 'https://segment.com', 9.0, true, 0, 'USD', '{"event_collection": true, "data_routing": true, "identity_resolution": true, "audience_builder": true, "privacy_controls": true}', '["Industry standard for customer data infrastructure","Routes data to 400+ downstream tools","Strong identity resolution across platforms","Excellent documentation and SDK support"]', '["Pricing escalates significantly with volume","Can be complex to implement correctly","Free tier limited to 1,000 visitors/month"]', '["Growth-stage companies building data infrastructure","Marketing teams needing unified customer profiles","Data teams routing events to warehouses and tools"]', 'Segment remains the definitive customer data platform, providing the data infrastructure foundation that enables marketing, product, and data teams to work from a single source of truth.', 'published');

-- ---------------------------------------------------------------------------
-- SAAS (+9 tools)
-- ---------------------------------------------------------------------------

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('notion-projects', 'Notion Projects', 'saas', 'Project Management', 'Project management built natively into Notion workspaces', 'Notion Projects brings full project management capabilities directly into Notion, including sprints, timelines, kanban boards, and calendar views. It features AI-powered project summaries, automated status updates, custom properties, and the unique ability to connect projects with all your other Notion documentation in a single workspace.', NULL, 'https://notion.so/product/projects', 8.5, true, 10, 'USD', '{"project_views": true, "sprints_and_timelines": true, "ai_summaries": true, "custom_properties": true, "connected_docs": true}', '["Projects live alongside documentation in one workspace","AI generates project summaries and standup updates","Flexible views including kanban, timeline, and calendar","Connected databases link tasks to specs and docs"]', '["Less specialized than Jira or Linear for engineering","Performance can lag with very large project databases","AI features require Notion AI add-on subscription"]', '["Teams already using Notion for documentation","Cross-functional teams needing projects linked to docs","Startups wanting one tool for docs and project management"]', 'Notion Projects is the strongest option for teams that want project management deeply connected to their documentation, eliminating the gap between planning and knowledge that plagues separate tools.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('shortcut-pm', 'Shortcut', 'saas', 'Project Management', 'Project management platform built for software teams at scale', 'Shortcut (formerly Clubhouse) is a project management platform designed specifically for software development teams. It provides stories, epics, milestones, and iterations with a clean interface, robust API, and deep Git integrations. It balances simplicity with the powerful features engineering teams need for planning, tracking, and shipping software.', NULL, 'https://shortcut.com', 8.3, true, 9, 'USD', '{"stories_and_epics": true, "milestones": true, "iterations": true, "git_integrations": true, "robust_api": true}', '["Clean interface that balances simplicity and power","Stories, epics, and milestones for multi-level planning","Deep GitHub, GitLab, and Bitbucket integrations","Generous free tier for small teams"]', '["Less well-known than Jira or Linear","Limited non-engineering PM features","Reporting less advanced than enterprise alternatives"]', '["Software teams needing a middle ground between Jira and Linear","Engineering organizations wanting API-first project management","Startups scaling from simple task tracking to structured PM"]', 'Shortcut hits the sweet spot between Jira''s complexity and simpler tools, offering thoughtful project management for software teams that want structure without bureaucracy.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('cal-com-platform', 'Cal.com', 'saas', 'Open-Source Scheduling', 'Open-source scheduling infrastructure for developers and businesses', 'Cal.com is an open-source scheduling platform that provides Calendly-like functionality with full customization and self-hosting capabilities. It offers event types, team scheduling, round-robin routing, payments, workflows, and a robust API, allowing businesses to build scheduling directly into their products or use it as a standalone booking tool.', NULL, 'https://cal.com', 8.4, true, 12, 'USD', '{"event_types": true, "team_scheduling": true, "round_robin_routing": true, "payment_collection": true, "api_and_webhooks": true}', '["Open-source with full self-hosting option","Highly customizable scheduling experience","API-first design for embedding in products","No per-seat pricing on self-hosted"]', '["Cloud version pricing per user","Self-hosting requires technical setup","Some advanced features still in development"]', '["Developers embedding scheduling into their products","Companies wanting open-source Calendly alternative","Teams needing fully customizable booking workflows"]', 'Cal.com is the strongest open-source scheduling platform, offering Calendly-level functionality with the customization and self-hosting options that developers and privacy-conscious organizations need.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('productboard', 'Productboard', 'saas', 'Product Management', 'Customer-driven product management platform for product teams', 'Productboard is a product management platform that helps teams understand what customers need, prioritize what to build, and align everyone around the product roadmap. It aggregates customer feedback from multiple sources, links insights to features, enables objective prioritization frameworks, and publishes interactive roadmaps for stakeholder communication.', NULL, 'https://productboard.com', 8.4, false, 20, 'USD', '{"customer_feedback_aggregation": true, "feature_prioritization": true, "roadmap_publishing": true, "insight_tracking": true, "stakeholder_alignment": true}', '["Connects customer feedback directly to product decisions","Prioritization frameworks enable objective feature ranking","Beautiful roadmap views for stakeholder communication","Integrates with Jira, Zendesk, Intercom, and Slack"]', '["No free tier available","Per-maker pricing adds up for larger PM teams","Setup and configuration takes significant effort"]', '["Product teams wanting customer-driven prioritization","Product managers consolidating feedback from multiple sources","Organizations needing shared roadmap visibility across teams"]', 'Productboard excels at closing the gap between customer feedback and product decisions, making it the top choice for product teams that want data-driven prioritization and transparent roadmap communication.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('huly', 'Huly', 'saas', 'Project Management', 'Open-source all-in-one project management platform', 'Huly is an open-source project management platform that combines issue tracking, team planning, knowledge management, and communication in one tool. It offers kanban boards, sprints, documents, chat, virtual office presence, and time tracking, positioning itself as an open-source alternative to Linear, Notion, and Slack combined.', NULL, 'https://huly.io', 7.9, true, 0, 'USD', '{"issue_tracking": true, "team_chat": true, "knowledge_base": true, "virtual_office": true, "time_tracking": true}', '["Open-source with self-hosting option","Combines PM, docs, and chat in one platform","Virtual office feature for team presence","Completely free for self-hosted deployments"]', '["Each module less deep than dedicated alternatives","Self-hosting requires significant infrastructure","Newer platform with less community support"]', '["Teams wanting to consolidate PM, docs, and chat tools","Organizations preferring open-source self-hosted solutions","Startups seeking an all-in-one workspace without costs"]', 'Huly is an ambitious open-source platform that consolidates project management, documentation, and communication into one tool, ideal for teams seeking simplicity and self-hosting.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('tawk-to', 'tawk.to', 'saas', 'Live Chat', 'Free live chat software for websites with full feature set', 'tawk.to is a free live chat application that provides real-time website visitor monitoring, customizable chat widgets, ticketing, knowledge base, and team management. Unlike most competitors, its core product is completely free with unlimited agents and chat history, monetizing through optional add-ons like removing branding and hiring chat agents.', NULL, 'https://tawk.to', 8.0, true, 0, 'USD', '{"live_chat_widget": true, "visitor_monitoring": true, "ticketing_system": true, "knowledge_base": true, "unlimited_agents": true}', '["Completely free with unlimited agents and history","Real-time visitor monitoring and engagement","Built-in ticketing and knowledge base","Customizable chat widget design"]', '["tawk.to branding on free tier","Support quality can be inconsistent","Interface design feels dated compared to Crisp or Intercom"]', '["Small businesses needing free live chat","Startups wanting customer support without costs","Websites needing real-time visitor monitoring"]', 'tawk.to delivers remarkable value as a completely free live chat platform with features that rival paid competitors, making it the obvious choice for budget-conscious businesses needing customer support.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('front', 'Front', 'saas', 'Shared Inbox', 'Shared inbox platform for team email and customer communication', 'Front is a shared inbox platform that brings team email, SMS, social media, and live chat into a single collaborative workspace. It combines the familiarity of email with helpdesk capabilities, enabling teams to assign, comment on, and collaboratively respond to messages while maintaining personal email-like communication with customers.', NULL, 'https://front.com', 8.5, false, 19, 'USD', '{"shared_inbox": true, "omnichannel_messaging": true, "team_collaboration": true, "workflow_automation": true, "analytics_and_reporting": true}', '["Email-like experience that teams adopt quickly","Omnichannel inbox unifies all communication","Internal comments and assignments for collaboration","Powerful automation rules for routing and tagging"]', '["No free tier available","Per-seat pricing adds up for larger teams","Advanced analytics require higher-tier plans"]', '["Customer-facing teams managing shared email accounts","Operations teams handling multi-channel communication","Companies wanting helpdesk features with email simplicity"]', 'Front uniquely combines the simplicity and personal feel of email with the collaboration and automation of a helpdesk, making it ideal for teams that want structure without losing the human touch.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('whereby', 'Whereby', 'saas', 'Video Conferencing', 'Browser-based video meetings with no downloads required', 'Whereby is a browser-based video conferencing platform that requires no downloads or installations for participants to join meetings. It provides permanent meeting rooms, screen sharing, recording, breakout groups, and an embeddable video API, focused on simplicity and ease of use for teams, educators, and telehealth providers.', NULL, 'https://whereby.com', 7.8, true, 7, 'USD', '{"browser_based": true, "permanent_rooms": true, "screen_sharing": true, "breakout_groups": true, "embeddable_api": true}', '["No downloads required for any participant","Permanent meeting room URLs are easy to share","Clean and simple interface","Embeddable video API for developers"]', '["Participant limits lower than Zoom or Teams","Fewer advanced features than full-featured platforms","Recording requires paid plans"]', '["Teams wanting frictionless video meetings","Developers embedding video into their applications","Educators and therapists needing simple video rooms"]', 'Whereby delivers the most frictionless video meeting experience available, proving that simplicity and no-download access matter more than feature count for most meeting scenarios.', 'published');

INSERT INTO tools (slug, name, category_slug, subcategory, headline, description, logo_url, website_url, rating, has_free_tier, pricing_start, pricing_currency, features, pros, cons, best_for, verdict, status) VALUES
('gather', 'Gather', 'saas', 'Virtual Office', 'Virtual office platform with spatial video for distributed teams', 'Gather is a virtual office platform that creates 2D spatial environments where remote team members can move around, see who is available, and have spontaneous video conversations by walking up to colleagues. It recreates the ambient awareness and casual interactions of a physical office, supporting daily standups, team events, and always-on collaboration.', NULL, 'https://gather.town', 8.1, true, 7, 'USD', '{"spatial_video": true, "customizable_offices": true, "proximity_chat": true, "event_spaces": true, "integrations": true}', '["Recreates spontaneous office interactions remotely","Spatial audio and video feel natural","Highly customizable virtual office layouts","Fun and engaging for team events and socials"]', '["Requires team commitment to keep the virtual office active","Can consume significant bandwidth","Novelty may wear off without cultural adoption"]', '["Distributed teams wanting office-like spontaneous interaction","Companies hosting virtual events and conferences","Remote teams struggling with isolation and disconnection"]', 'Gather uniquely solves the spontaneous interaction problem in remote work, providing spatial presence that brings teams together in ways that scheduled video calls simply cannot replicate.', 'published');

-- =============================================================================
-- END OF 22-more-tools.sql (50 tools total)
-- ai-tools: 9 (google-veo, replit-ai, openai-sora, hugging-face, replicate,
--              notion-ai-assistant, together-ai, tldraw, pieces-for-developers)
-- business: 8 (fellow, trainual, calendly-routing, lucidchart, mixmax,
--              reclaim-ai, sunsama, pitch)
-- ecommerce: 8 (fourthwall, shopify-markets, junip, rebuy, zettle,
--               stamped-io, shogun, loop-returns)
-- hosting: 8 (supabase, planetscale, neon, upstash, deno-deploy, coolify,
--             turso, dokku)
-- marketing: 8 (lemlist, clay, sprig, amplitude, customer-io-data-pipelines,
--               mixpanel, resend, segment)
-- saas: 9 (notion-projects, shortcut-pm, cal-com-platform, productboard, huly,
--          tawk-to, front, whereby, gather)
-- =============================================================================
